import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type LangCode = string;

export const LANGUAGES: { code: LangCode; name: string; native: string; dir?: "rtl" }[] = [
  { code: "en", name: "English", native: "English" },
  { code: "hi", name: "Hindi", native: "हिन्दी" },
  { code: "bn", name: "Bengali", native: "বাংলা" },
  { code: "te", name: "Telugu", native: "తెలుగు" },
  { code: "ta", name: "Tamil", native: "தமிழ்" },
  { code: "mr", name: "Marathi", native: "मराठी" },
  { code: "gu", name: "Gujarati", native: "ગુજરાતી" },
  { code: "kn", name: "Kannada", native: "ಕನ್ನಡ" },
  { code: "ml", name: "Malayalam", native: "മലയാളം" },
  { code: "pa", name: "Punjabi", native: "ਪੰਜਾਬੀ" },
  { code: "or", name: "Odia", native: "ଓଡ଼ିଆ" },
  { code: "as", name: "Assamese", native: "অসমীয়া" },
  { code: "ur", name: "Urdu", native: "اردو", dir: "rtl" },
  { code: "ne", name: "Nepali", native: "नेपाली" },
  { code: "si", name: "Sinhala", native: "සිංහල" },
  { code: "zh", name: "Chinese", native: "中文" },
  { code: "ja", name: "Japanese", native: "日本語" },
  { code: "ko", name: "Korean", native: "한국어" },
  { code: "es", name: "Spanish", native: "Español" },
  { code: "fr", name: "French", native: "Français" },
  { code: "de", name: "German", native: "Deutsch" },
  { code: "pt", name: "Portuguese", native: "Português" },
  { code: "ru", name: "Russian", native: "Русский" },
  { code: "ar", name: "Arabic", native: "العربية", dir: "rtl" },
  { code: "tr", name: "Turkish", native: "Türkçe" },
  { code: "vi", name: "Vietnamese", native: "Tiếng Việt" },
  { code: "th", name: "Thai", native: "ไทย" },
  { code: "id", name: "Indonesian", native: "Bahasa Indonesia" },
  { code: "ms", name: "Malay", native: "Bahasa Melayu" },
  { code: "fil", name: "Filipino", native: "Filipino" },
  { code: "it", name: "Italian", native: "Italiano" },
  { code: "nl", name: "Dutch", native: "Nederlands" },
  { code: "pl", name: "Polish", native: "Polski" },
  { code: "uk", name: "Ukrainian", native: "Українська" },
  { code: "cs", name: "Czech", native: "Čeština" },
  { code: "sk", name: "Slovak", native: "Slovenčina" },
  { code: "ro", name: "Romanian", native: "Română" },
  { code: "hu", name: "Hungarian", native: "Magyar" },
  { code: "sv", name: "Swedish", native: "Svenska" },
  { code: "da", name: "Danish", native: "Dansk" },
  { code: "no", name: "Norwegian", native: "Norsk" },
  { code: "fi", name: "Finnish", native: "Suomi" },
  { code: "el", name: "Greek", native: "Ελληνικά" },
  { code: "bg", name: "Bulgarian", native: "Български" },
  { code: "hr", name: "Croatian", native: "Hrvatski" },
  { code: "sr", name: "Serbian", native: "Српски" },
  { code: "he", name: "Hebrew", native: "עברית", dir: "rtl" },
  { code: "fa", name: "Persian", native: "فارسی", dir: "rtl" },
  { code: "sw", name: "Swahili", native: "Kiswahili" },
  { code: "am", name: "Amharic", native: "አማርኛ" },
  { code: "my", name: "Burmese", native: "မြန်မာ" },
  { code: "km", name: "Khmer", native: "ខ្មែរ" },
  { code: "lo", name: "Lao", native: "ລາວ" },
  { code: "ka", name: "Georgian", native: "ქართული" },
  { code: "hy", name: "Armenian", native: "Հայերեն" },
  { code: "az", name: "Azerbaijani", native: "Azərbaycan" },
  { code: "uz", name: "Uzbek", native: "O'zbek" },
  { code: "kk", name: "Kazakh", native: "Қазақ" },
  { code: "mn", name: "Mongolian", native: "Монгол" },
  { code: "et", name: "Estonian", native: "Eesti" },
  { code: "lv", name: "Latvian", native: "Latviešu" },
  { code: "lt", name: "Lithuanian", native: "Lietuvių" },
];

type TranslationMap = Record<string, string>;
type Translations = Record<LangCode, TranslationMap>;

// Full English translations — every section
const en: TranslationMap = {
  // Nav
  "nav.build": "Build",
  "nav.products": "Products",
  "nav.explorer": "Explorer",
  "nav.usecases": "Use Cases",
  "nav.grants": "Grants",
  "nav.ambassador": "Ambassador",
  "nav.academy": "Academy",
  "nav.join": "Join Ecosystem",

  // Hero
  "hero.badge": "Next-Gen EVM Layer-1 Blockchain",
  "hero.title1": "ENGINEERING",
  "hero.desc": "MST Blockchain is a next-generation EVM Compatible Layer-1 blockchain, designed to make Web3",
  "hero.desc2": "secure, accessible, and affordable",
  "hero.desc3": "for everyone.",
  "hero.explore": "Explore Ecosystem",
  "hero.docs": "Read Docs",
  "hero.validators": "Validators",
  "hero.wallets": "Wallets Created",
  "hero.users": "Registered Users",
  "hero.blocktime": "Block Time",

  // SARAL
  "saral.simple": "Simple",
  "saral.accessible": "Accessible",
  "saral.reliable": "Reliable",
  "saral.affordable": "Affordable",
  "saral.limitless": "Limitless",

  // WhatIsMST
  "what.label": "01 / Foundation",
  "what.title": "What is",
  "what.desc": "MST Blockchain is a next-generation EVM Compatible Layer-1 blockchain designed to make Web3 secure, accessible, and affordable for everyone.",
  "what.consensus": "Consensus",
  "what.posa": "Proof of Staked Authority",
  "what.blocktime": "3s block time · EVM compatible",
  "what.evm.title": "EVM Compatible",
  "what.evm.desc": "Fully compatible with Ethereum Virtual Machine. Deploy your existing Solidity smart contracts directly on MST with zero modifications.",
  "what.evm.cta": "View Architecture",
  "what.evm.accent": "Layer-1 Infrastructure",
  "what.posa.title": "PoSA Consensus",
  "what.posa.desc": "Proof of Staked Authority consensus mechanism with 69,000+ validators securing the network. 3-second block time with deterministic finality.",
  "what.posa.cta": "Explore Validators",
  "what.posa.accent": "69K+ Validators",
  "what.saral.title": "SARAL Framework",
  "what.saral.desc": "Simple, Accessible, Reliable, Affordable, and Limitless. Our infrastructure philosophy ensures Web3 is accessible to everyone.",
  "what.saral.cta": "Learn SARAL",
  "what.saral.accent": "Built for Everyone",

  // Products
  "products.label": "SARAL Infrastructure",
  "products.title": "Ecosystem",
  "products.title2": "Products",
  "products.explore": "Explore",

  // Validator
  "validator.join": "Join",
  "validator.validators": "Validators",
  "validator.desc": "Help secure the MST network using Proof of Staked Authority consensus.",
  "validator.active": "Active Validators",
  "validator.uptime": "Network Uptime",
  "validator.blocktime": "Block Time",
  "validator.become": "Become a Validator",

  // Explorer
  "explorer.label": "Live Network",
  "explorer.title": "MST Network",
  "explorer.title2": "Explorer",
  "explorer.live": "Live — 3s Block Time",
  "explorer.totalTx": "Total Transactions",
  "explorer.gasPrice": "Gas Price",
  "explorer.avgBlock": "Avg Block Time",
  "explorer.activeVal": "Active Validators",
  "explorer.latestBlocks": "Latest Blocks",
  "explorer.latestTx": "Latest Transactions",
  "explorer.visit": "Visit MSTScan Explorer",

  // Ecosystem
  "eco.label": "Growing Community",
  "eco.title": "Join Our",
  "eco.title2": "Ecosystem",
  "eco.desc": "300,000+ registered users and growing. Be part of the SARAL revolution.",
  "eco.partner": "Become a Partner",
  "eco.validator.title": "Validator",
  "eco.validator.desc": "Secure the MST network using PoSA consensus and earn staking rewards. Join 69,000+ validators worldwide.",
  "eco.validator.metric": "69K+ active",
  "eco.ambassador.title": "Ambassador",
  "eco.ambassador.desc": "Represent MST globally. Create content, host events, and grow the Web3 community across regions.",
  "eco.ambassador.metric": "Global reach",
  "eco.grants.title": "Grants",
  "eco.grants.desc": "Apply for funding to build innovative dApps, tools, and infrastructure on the MST network.",
  "eco.grants.metric": "Open applications",
  "eco.developer.title": "Developer",
  "eco.developer.desc": "Build with full EVM compatibility. Deploy Solidity contracts, use familiar tools, and access our SDK.",
  "eco.developer.metric": "EVM compatible",

  // Use Cases
  "usecases.label": "20+ Industries",
  "usecases.title": "Use Cases",
  "usecases.desc": "MST Protocol powers mission-critical applications across industries. Hover to preview, click to dive deep.",

  // Blogs
  "blogs.label": "Stay Updated",
  "blogs.title": "Latest",
  "blogs.title2": "Updates",
  "blogs.readMore": "Read More",

  // Security Banner
  "security.label": "Secured by PoSA Consensus",
  "security.title": "Built on",
  "security.title2": "Structural Purity.",
  "security.desc": "69,000+ validators, 161,000+ wallets, 300,000+ users — and growing every day.",
  "security.readDocs": "Read the Documentation",

  // Footer
  "footer.desc": "Next-gen EVM Compatible Layer-1 blockchain. SARAL infrastructure for real-world Web3 adoption.",
  "footer.ecosystem": "Ecosystem",
  "footer.resources": "Resources",
  "footer.contact": "Contact",
  "footer.newsletter": "Newsletter",
  "footer.submit": "Submit",
  "footer.rights": "© 2025 MST Blockchain. ALL RIGHTS RESERVED. SARAL — SIMPLE, ACCESSIBLE, RELIABLE, AFFORDABLE, LIMITLESS.",
  "footer.emailPlaceholder": "YOUR EMAIL",

  // Grants Page
  "grants.back": "Back to Home",
  "grants.label": "Funding Innovation",
  "grants.title": "MST Grants",
  "grants.title2": "Program",
  "grants.desc": "Supporting builders, researchers, and teams creating real-world blockchain solutions on MST.",
  "grants.apply": "Apply Now",
  "grants.requirements": "Requirements",
  "grants.deliverables": "Deliverables",
  "grants.process": "Application Process",

  // Ambassador Page
  "amb.back": "Back to Home",
  "amb.label": "Join the Movement",
  "amb.title": "MST Ambassador",
  "amb.title2": "Program",
  "amb.desc": "Represent MST in your region, industry, or campus. Help bring Web3 to the world.",
  "amb.apply": "Apply Now",
  "amb.perks": "Perks",
  "amb.benefits": "Program Benefits",

  // Academy Page
  "academy.back": "Back to Home",
  "academy.label": "Learn Web3",
  "academy.title": "MST",
  "academy.title2": "Academy",
  "academy.desc": "Master blockchain development from fundamentals to advanced deployment on MST.",
  "academy.allModules": "All Modules",
  "academy.fundamentals": "Fundamentals",
  "academy.architecture": "Architecture",
  "academy.development": "Development",
  "academy.deployment": "Deployment",
  "academy.security": "Security",
  "academy.lessons": "Lessons",
  "academy.assessment": "Assessment",
  "academy.passingScore": "Passing Score",
  "academy.startModule": "Start Module",
};

const hi: TranslationMap = {
  "nav.build": "बनाएं", "nav.products": "उत्पाद", "nav.explorer": "एक्सप्लोरर", "nav.usecases": "उपयोग", "nav.grants": "अनुदान", "nav.ambassador": "राजदूत", "nav.academy": "अकादमी", "nav.join": "इकोसिस्टम जुड़ें",
  "hero.badge": "नेक्स्ट-जेन EVM लेयर-1 ब्लॉकचेन", "hero.title1": "इंजीनियरिंग", "hero.desc": "MST ब्लॉकचेन एक अगली पीढ़ी का EVM संगत लेयर-1 ब्लॉकचेन है, जिसे Web3 को", "hero.desc2": "सुरक्षित, सुलभ और किफायती", "hero.desc3": "सभी के लिए बनाया गया है।", "hero.explore": "इकोसिस्टम खोजें", "hero.docs": "डॉक्स पढ़ें",
  "hero.validators": "वैलिडेटर", "hero.wallets": "वॉलेट बनाए गए", "hero.users": "पंजीकृत उपयोगकर्ता", "hero.blocktime": "ब्लॉक टाइम",
  "saral.simple": "सरल", "saral.accessible": "सुलभ", "saral.reliable": "विश्वसनीय", "saral.affordable": "किफायती", "saral.limitless": "असीमित",
  "what.label": "01 / नींव", "what.title": "क्या है", "what.desc": "MST ब्लॉकचेन एक अगली पीढ़ी का EVM संगत लेयर-1 ब्लॉकचेन है जिसे Web3 को सुरक्षित, सुलभ और किफायती बनाने के लिए डिज़ाइन किया गया है।",
  "what.consensus": "सहमति", "what.posa": "प्रूफ ऑफ स्टेक्ड अथॉरिटी", "what.blocktime": "3s ब्लॉक टाइम · EVM संगत",
  "what.evm.title": "EVM संगत", "what.evm.desc": "एथेरियम वर्चुअल मशीन के साथ पूरी तरह संगत। अपने मौजूदा सॉलिडिटी स्मार्ट कॉन्ट्रैक्ट्स सीधे MST पर बिना किसी बदलाव के तैनात करें।", "what.evm.cta": "आर्किटेक्चर देखें", "what.evm.accent": "लेयर-1 इन्फ्रास्ट्रक्चर",
  "what.posa.title": "PoSA सहमति", "what.posa.desc": "69,000+ वैलिडेटर्स द्वारा सुरक्षित नेटवर्क के साथ प्रूफ ऑफ स्टेक्ड अथॉरिटी सहमति तंत्र। 3 सेकंड ब्लॉक टाइम।", "what.posa.cta": "वैलिडेटर्स खोजें", "what.posa.accent": "69K+ वैलिडेटर्स",
  "what.saral.title": "SARAL फ्रेमवर्क", "what.saral.desc": "सरल, सुलभ, विश्वसनीय, किफायती और असीमित। हमारा इन्फ्रास्ट्रक्चर दर्शन।", "what.saral.cta": "SARAL जानें", "what.saral.accent": "सबके लिए बना",
  "products.label": "SARAL इन्फ्रास्ट्रक्चर", "products.title": "इकोसिस्टम", "products.title2": "उत्पाद", "products.explore": "खोजें",
  "validator.join": "जुड़ें", "validator.validators": "वैलिडेटर्स", "validator.desc": "प्रूफ ऑफ स्टेक्ड अथॉरिटी सहमति का उपयोग करके MST नेटवर्क को सुरक्षित करने में मदद करें।",
  "validator.active": "सक्रिय वैलिडेटर", "validator.uptime": "नेटवर्क अपटाइम", "validator.blocktime": "ब्लॉक टाइम", "validator.become": "वैलिडेटर बनें",
  "explorer.label": "लाइव नेटवर्क", "explorer.title": "MST नेटवर्क", "explorer.title2": "एक्सप्लोरर", "explorer.live": "लाइव — 3s ब्लॉक टाइम",
  "explorer.totalTx": "कुल लेनदेन", "explorer.gasPrice": "गैस मूल्य", "explorer.avgBlock": "औसत ब्लॉक टाइम", "explorer.activeVal": "सक्रिय वैलिडेटर",
  "explorer.latestBlocks": "नवीनतम ब्लॉक", "explorer.latestTx": "नवीनतम लेनदेन", "explorer.visit": "MSTScan एक्सप्लोरर देखें",
  "eco.label": "बढ़ता समुदाय", "eco.title": "हमारे", "eco.title2": "इकोसिस्टम से जुड़ें", "eco.desc": "3,00,000+ पंजीकृत उपयोगकर्ता और बढ़ रहे हैं। SARAL क्रांति का हिस्सा बनें।", "eco.partner": "पार्टनर बनें",
  "eco.validator.title": "वैलिडेटर", "eco.validator.desc": "PoSA सहमति का उपयोग करके MST नेटवर्क सुरक्षित करें और स्टेकिंग पुरस्कार अर्जित करें।", "eco.validator.metric": "69K+ सक्रिय",
  "eco.ambassador.title": "राजदूत", "eco.ambassador.desc": "MST का विश्व स्तर पर प्रतिनिधित्व करें। सामग्री बनाएं, कार्यक्रम आयोजित करें।", "eco.ambassador.metric": "वैश्विक पहुंच",
  "eco.grants.title": "अनुदान", "eco.grants.desc": "MST नेटवर्क पर अभिनव dApps, टूल्स और इन्फ्रास्ट्रक्चर बनाने के लिए फंडिंग के लिए आवेदन करें।", "eco.grants.metric": "आवेदन खुले",
  "eco.developer.title": "डेवलपर", "eco.developer.desc": "पूर्ण EVM संगतता के साथ बनाएं। सॉलिडिटी कॉन्ट्रैक्ट तैनात करें।", "eco.developer.metric": "EVM संगत",
  "usecases.label": "20+ उद्योग", "usecases.title": "उपयोग के मामले", "usecases.desc": "MST प्रोटोकॉल उद्योगों में मिशन-क्रिटिकल एप्लिकेशन को शक्ति प्रदान करता है।",
  "blogs.label": "अपडेट रहें", "blogs.title": "नवीनतम", "blogs.title2": "अपडेट", "blogs.readMore": "और पढ़ें",
  "security.label": "PoSA सहमति द्वारा सुरक्षित", "security.title": "पर बना", "security.title2": "संरचनात्मक शुद्धता।", "security.desc": "69,000+ वैलिडेटर, 161,000+ वॉलेट, 300,000+ उपयोगकर्ता — और हर दिन बढ़ रहे हैं।", "security.readDocs": "डॉक्यूमेंटेशन पढ़ें",
  "footer.desc": "अगली पीढ़ी का EVM संगत लेयर-1 ब्लॉकचेन। वास्तविक दुनिया Web3 अपनाने के लिए SARAL इन्फ्रास्ट्रक्चर।",
  "footer.ecosystem": "इकोसिस्टम", "footer.resources": "संसाधन", "footer.contact": "संपर्क", "footer.newsletter": "समाचार पत्र", "footer.submit": "जमा करें",
  "footer.rights": "© 2025 MST ब्लॉकचेन। सर्वाधिकार सुरक्षित।", "footer.emailPlaceholder": "आपका ईमेल",
  "grants.back": "होम पर वापस", "grants.label": "नवाचार को फंडिंग", "grants.title": "MST अनुदान", "grants.title2": "कार्यक्रम",
  "grants.desc": "MST पर वास्तविक दुनिया के ब्लॉकचेन समाधान बनाने वाले बिल्डरों, शोधकर्ताओं और टीमों का समर्थन।",
  "grants.apply": "अभी आवेदन करें", "grants.requirements": "आवश्यकताएं", "grants.deliverables": "डिलिवरेबल्स", "grants.process": "आवेदन प्रक्रिया",
  "amb.back": "होम पर वापस", "amb.label": "आंदोलन से जुड़ें", "amb.title": "MST राजदूत", "amb.title2": "कार्यक्रम",
  "amb.desc": "अपने क्षेत्र, उद्योग या कैंपस में MST का प्रतिनिधित्व करें। Web3 को दुनिया में लाने में मदद करें।",
  "amb.apply": "अभी आवेदन करें", "amb.perks": "लाभ", "amb.benefits": "कार्यक्रम लाभ",
  "academy.back": "होम पर वापस", "academy.label": "Web3 सीखें", "academy.title": "MST", "academy.title2": "अकादमी",
  "academy.desc": "MST पर बुनियादी बातों से लेकर उन्नत डिप्लॉयमेंट तक ब्लॉकचेन डेवलपमेंट में महारत हासिल करें।",
  "academy.allModules": "सभी मॉड्यूल", "academy.fundamentals": "बुनियादी बातें", "academy.architecture": "आर्किटेक्चर",
  "academy.development": "डेवलपमेंट", "academy.deployment": "डिप्लॉयमेंट", "academy.security": "सुरक्षा",
  "academy.lessons": "पाठ", "academy.assessment": "मूल्यांकन", "academy.passingScore": "उत्तीर्ण अंक", "academy.startModule": "मॉड्यूल शुरू करें",
};

const zh: TranslationMap = {
  "nav.build": "构建", "nav.products": "产品", "nav.explorer": "浏览器", "nav.usecases": "用例", "nav.grants": "资助", "nav.ambassador": "大使", "nav.academy": "学院", "nav.join": "加入生态",
  "hero.badge": "下一代 EVM Layer-1 区块链", "hero.title1": "工程", "hero.desc": "MST区块链是下一代EVM兼容Layer-1区块链，旨在使Web3", "hero.desc2": "安全、可访问且经济实惠", "hero.desc3": "面向所有人。", "hero.explore": "探索生态", "hero.docs": "阅读文档",
  "hero.validators": "验证者", "hero.wallets": "已创建钱包", "hero.users": "注册用户", "hero.blocktime": "出块时间",
  "saral.simple": "简单", "saral.accessible": "可访问", "saral.reliable": "可靠", "saral.affordable": "实惠", "saral.limitless": "无限",
  "what.label": "01 / 基础", "what.title": "什么是", "what.desc": "MST区块链是下一代EVM兼容Layer-1区块链，旨在使Web3安全、可访问且经济实惠。",
  "what.consensus": "共识", "what.posa": "权益质押权威证明", "what.blocktime": "3秒出块 · EVM兼容",
  "what.evm.title": "EVM兼容", "what.evm.desc": "完全兼容以太坊虚拟机。直接在MST上部署现有的Solidity智能合约，无需任何修改。", "what.evm.cta": "查看架构", "what.evm.accent": "Layer-1基础设施",
  "what.posa.title": "PoSA共识", "what.posa.desc": "69,000+验证者保护网络的权益质押权威共识机制。3秒出块时间。", "what.posa.cta": "探索验证者", "what.posa.accent": "69K+验证者",
  "what.saral.title": "SARAL框架", "what.saral.desc": "简单、可访问、可靠、实惠且无限。我们的基础设施理念。", "what.saral.cta": "了解SARAL", "what.saral.accent": "为所有人而建",
  "products.label": "SARAL基础设施", "products.title": "生态", "products.title2": "产品", "products.explore": "探索",
  "validator.join": "加入", "validator.validators": "验证者", "validator.desc": "使用权益质押权威共识帮助保护MST网络。",
  "validator.active": "活跃验证者", "validator.uptime": "网络正常运行", "validator.blocktime": "出块时间", "validator.become": "成为验证者",
  "explorer.label": "实时网络", "explorer.title": "MST网络", "explorer.title2": "浏览器", "explorer.live": "实时 — 3秒出块",
  "explorer.totalTx": "总交易数", "explorer.gasPrice": "Gas价格", "explorer.avgBlock": "平均出块时间", "explorer.activeVal": "活跃验证者",
  "explorer.latestBlocks": "最新区块", "explorer.latestTx": "最新交易", "explorer.visit": "访问MSTScan浏览器",
  "eco.label": "成长中的社区", "eco.title": "加入我们的", "eco.title2": "生态系统", "eco.desc": "300,000+注册用户持续增长。成为SARAL革命的一部分。", "eco.partner": "成为合作伙伴",
  "eco.validator.title": "验证者", "eco.validator.desc": "使用PoSA共识保护MST网络并获得质押奖励。", "eco.validator.metric": "69K+活跃",
  "eco.ambassador.title": "大使", "eco.ambassador.desc": "在全球代表MST。创建内容，举办活动。", "eco.ambassador.metric": "全球覆盖",
  "eco.grants.title": "资助", "eco.grants.desc": "申请资金在MST网络上构建创新的dApp和工具。", "eco.grants.metric": "申请开放",
  "eco.developer.title": "开发者", "eco.developer.desc": "完全EVM兼容。部署Solidity合约。", "eco.developer.metric": "EVM兼容",
  "usecases.label": "20+行业", "usecases.title": "用例", "usecases.desc": "MST协议为各行业的关键任务应用提供动力。",
  "blogs.label": "保持更新", "blogs.title": "最新", "blogs.title2": "动态", "blogs.readMore": "阅读更多",
  "security.label": "PoSA共识保护", "security.title": "建立在", "security.title2": "结构纯度之上。", "security.desc": "69,000+验证者，161,000+钱包，300,000+用户——每天都在增长。", "security.readDocs": "阅读文档",
  "footer.desc": "下一代EVM兼容Layer-1区块链。面向现实世界Web3采用的SARAL基础设施。",
  "footer.ecosystem": "生态系统", "footer.resources": "资源", "footer.contact": "联系", "footer.newsletter": "通讯", "footer.submit": "提交",
  "footer.rights": "© 2025 MST区块链。保留所有权利。", "footer.emailPlaceholder": "您的邮箱",
  "grants.back": "返回首页", "grants.label": "资助创新", "grants.title": "MST资助", "grants.title2": "计划", "grants.desc": "支持在MST上创建现实世界区块链解决方案的建设者。",
  "grants.apply": "立即申请", "grants.requirements": "要求", "grants.deliverables": "交付成果", "grants.process": "申请流程",
  "amb.back": "返回首页", "amb.label": "加入运动", "amb.title": "MST大使", "amb.title2": "计划", "amb.desc": "在您的地区代表MST。帮助将Web3带给世界。",
  "amb.apply": "立即申请", "amb.perks": "福利", "amb.benefits": "计划福利",
  "academy.back": "返回首页", "academy.label": "学习Web3", "academy.title": "MST", "academy.title2": "学院", "academy.desc": "从基础到高级部署，掌握MST上的区块链开发。",
  "academy.allModules": "所有模块", "academy.fundamentals": "基础", "academy.architecture": "架构", "academy.development": "开发", "academy.deployment": "部署", "academy.security": "安全",
  "academy.lessons": "课程", "academy.assessment": "评估", "academy.passingScore": "及格分数", "academy.startModule": "开始模块",
};

const es: TranslationMap = {
  "nav.build": "Construir", "nav.products": "Productos", "nav.explorer": "Explorador", "nav.usecases": "Casos de Uso", "nav.grants": "Subvenciones", "nav.ambassador": "Embajador", "nav.academy": "Academia", "nav.join": "Unirse al Ecosistema",
  "hero.badge": "Blockchain EVM Layer-1 de Nueva Generación", "hero.title1": "INGENIERÍA", "hero.desc": "MST Blockchain es una blockchain Layer-1 compatible con EVM de nueva generación, diseñada para hacer Web3", "hero.desc2": "seguro, accesible y asequible", "hero.desc3": "para todos.", "hero.explore": "Explorar Ecosistema", "hero.docs": "Leer Docs",
  "hero.validators": "Validadores", "hero.wallets": "Billeteras Creadas", "hero.users": "Usuarios Registrados", "hero.blocktime": "Tiempo de Bloque",
  "saral.simple": "Simple", "saral.accessible": "Accesible", "saral.reliable": "Confiable", "saral.affordable": "Asequible", "saral.limitless": "Sin Límites",
  "what.label": "01 / Fundación", "what.title": "¿Qué es", "what.desc": "MST Blockchain es una blockchain Layer-1 compatible con EVM de nueva generación diseñada para hacer Web3 seguro, accesible y asequible.",
  "what.consensus": "Consenso", "what.posa": "Prueba de Autoridad Apostada", "what.blocktime": "3s bloque · Compatible EVM",
  "what.evm.title": "Compatible EVM", "what.evm.desc": "Totalmente compatible con la Máquina Virtual de Ethereum. Despliega tus contratos Solidity directamente en MST sin modificaciones.", "what.evm.cta": "Ver Arquitectura", "what.evm.accent": "Infraestructura Layer-1",
  "what.posa.title": "Consenso PoSA", "what.posa.desc": "Mecanismo de consenso con 69,000+ validadores asegurando la red. Bloque de 3 segundos.", "what.posa.cta": "Explorar Validadores", "what.posa.accent": "69K+ Validadores",
  "what.saral.title": "Framework SARAL", "what.saral.desc": "Simple, Accesible, Confiable, Asequible e Ilimitado. Nuestra filosofía de infraestructura.", "what.saral.cta": "Aprender SARAL", "what.saral.accent": "Para Todos",
  "products.label": "Infraestructura SARAL", "products.title": "Ecosistema", "products.title2": "Productos", "products.explore": "Explorar",
  "validator.join": "Únete a", "validator.validators": "Validadores", "validator.desc": "Ayuda a asegurar la red MST usando consenso PoSA.",
  "validator.active": "Validadores Activos", "validator.uptime": "Tiempo Activo", "validator.blocktime": "Tiempo de Bloque", "validator.become": "Conviértete en Validador",
  "explorer.label": "Red en Vivo", "explorer.title": "Red MST", "explorer.title2": "Explorador", "explorer.live": "En Vivo — 3s Bloque",
  "explorer.totalTx": "Total Transacciones", "explorer.gasPrice": "Precio Gas", "explorer.avgBlock": "Tiempo Promedio", "explorer.activeVal": "Validadores Activos",
  "explorer.latestBlocks": "Últimos Bloques", "explorer.latestTx": "Últimas Transacciones", "explorer.visit": "Visitar MSTScan",
  "eco.label": "Comunidad Creciente", "eco.title": "Únete a Nuestro", "eco.title2": "Ecosistema", "eco.desc": "300,000+ usuarios registrados y creciendo. Sé parte de la revolución SARAL.", "eco.partner": "Ser Socio",
  "eco.validator.title": "Validador", "eco.validator.desc": "Asegura la red MST y gana recompensas de staking.", "eco.validator.metric": "69K+ activos",
  "eco.ambassador.title": "Embajador", "eco.ambassador.desc": "Representa MST globalmente. Crea contenido y organiza eventos.", "eco.ambassador.metric": "Alcance global",
  "eco.grants.title": "Subvenciones", "eco.grants.desc": "Solicita financiación para construir dApps innovadoras en MST.", "eco.grants.metric": "Solicitudes abiertas",
  "eco.developer.title": "Desarrollador", "eco.developer.desc": "Construye con compatibilidad EVM completa.", "eco.developer.metric": "Compatible EVM",
  "usecases.label": "20+ Industrias", "usecases.title": "Casos de Uso", "usecases.desc": "MST impulsa aplicaciones críticas en todas las industrias.",
  "blogs.label": "Mantente Actualizado", "blogs.title": "Últimas", "blogs.title2": "Novedades", "blogs.readMore": "Leer Más",
  "security.label": "Asegurado por Consenso PoSA", "security.title": "Construido sobre", "security.title2": "Pureza Estructural.", "security.desc": "69,000+ validadores, 161,000+ billeteras, 300,000+ usuarios — creciendo cada día.", "security.readDocs": "Leer Documentación",
  "footer.desc": "Blockchain Layer-1 de nueva generación compatible con EVM. Infraestructura SARAL.", "footer.ecosystem": "Ecosistema", "footer.resources": "Recursos", "footer.contact": "Contacto", "footer.newsletter": "Boletín", "footer.submit": "Enviar",
  "footer.rights": "© 2025 MST Blockchain. TODOS LOS DERECHOS RESERVADOS.", "footer.emailPlaceholder": "TU EMAIL",
  "grants.back": "Volver", "grants.label": "Financiando Innovación", "grants.title": "Subvenciones MST", "grants.title2": "Programa", "grants.desc": "Apoyando constructores y equipos.", "grants.apply": "Aplicar Ahora", "grants.requirements": "Requisitos", "grants.deliverables": "Entregables", "grants.process": "Proceso",
  "amb.back": "Volver", "amb.label": "Únete al Movimiento", "amb.title": "Embajador MST", "amb.title2": "Programa", "amb.desc": "Representa MST en tu región.", "amb.apply": "Aplicar Ahora", "amb.perks": "Beneficios", "amb.benefits": "Beneficios del Programa",
  "academy.back": "Volver", "academy.label": "Aprende Web3", "academy.title": "MST", "academy.title2": "Academia", "academy.desc": "Domina el desarrollo blockchain.", "academy.allModules": "Todos", "academy.fundamentals": "Fundamentos", "academy.architecture": "Arquitectura", "academy.development": "Desarrollo", "academy.deployment": "Despliegue", "academy.security": "Seguridad", "academy.lessons": "Lecciones", "academy.assessment": "Evaluación", "academy.passingScore": "Nota Mínima", "academy.startModule": "Iniciar Módulo",
};

const fr: TranslationMap = {
  "nav.build": "Construire", "nav.products": "Produits", "nav.explorer": "Explorateur", "nav.usecases": "Cas d'Usage", "nav.grants": "Subventions", "nav.ambassador": "Ambassadeur", "nav.academy": "Académie", "nav.join": "Rejoindre l'Écosystème",
  "hero.badge": "Blockchain EVM Layer-1 Nouvelle Génération", "hero.title1": "INGÉNIERIE", "hero.desc": "MST Blockchain est une blockchain Layer-1 compatible EVM de nouvelle génération, conçue pour rendre Web3", "hero.desc2": "sécurisé, accessible et abordable", "hero.desc3": "pour tous.", "hero.explore": "Explorer l'Écosystème", "hero.docs": "Lire la Doc",
  "hero.validators": "Validateurs", "hero.wallets": "Portefeuilles Créés", "hero.users": "Utilisateurs Inscrits", "hero.blocktime": "Temps de Bloc",
  "saral.simple": "Simple", "saral.accessible": "Accessible", "saral.reliable": "Fiable", "saral.affordable": "Abordable", "saral.limitless": "Illimité",
  "what.label": "01 / Fondation", "what.title": "Qu'est-ce que", "what.desc": "MST Blockchain est une blockchain Layer-1 compatible EVM de nouvelle génération.",
  "what.consensus": "Consensus", "what.posa": "Preuve d'Autorité Stakée", "what.blocktime": "3s bloc · Compatible EVM",
  "what.evm.title": "Compatible EVM", "what.evm.desc": "Entièrement compatible avec la Machine Virtuelle Ethereum. Déployez vos contrats Solidity directement.", "what.evm.cta": "Voir l'Architecture", "what.evm.accent": "Infrastructure Layer-1",
  "what.posa.title": "Consensus PoSA", "what.posa.desc": "Mécanisme de consensus avec 69,000+ validateurs. Bloc de 3 secondes.", "what.posa.cta": "Explorer les Validateurs", "what.posa.accent": "69K+ Validateurs",
  "what.saral.title": "Framework SARAL", "what.saral.desc": "Simple, Accessible, Fiable, Abordable et Illimité.", "what.saral.cta": "Apprendre SARAL", "what.saral.accent": "Pour Tous",
  "products.label": "Infrastructure SARAL", "products.title": "Écosystème", "products.title2": "Produits", "products.explore": "Explorer",
  "validator.join": "Rejoignez", "validator.validators": "Validateurs", "validator.desc": "Aidez à sécuriser le réseau MST.", "validator.active": "Validateurs Actifs", "validator.uptime": "Disponibilité", "validator.blocktime": "Temps de Bloc", "validator.become": "Devenir Validateur",
  "explorer.label": "Réseau en Direct", "explorer.title": "Réseau MST", "explorer.title2": "Explorateur", "explorer.live": "En Direct — 3s Bloc",
  "explorer.totalTx": "Total Transactions", "explorer.gasPrice": "Prix du Gas", "explorer.avgBlock": "Temps Moyen", "explorer.activeVal": "Validateurs Actifs",
  "explorer.latestBlocks": "Derniers Blocs", "explorer.latestTx": "Dernières Transactions", "explorer.visit": "Visiter MSTScan",
  "eco.label": "Communauté Croissante", "eco.title": "Rejoignez Notre", "eco.title2": "Écosystème", "eco.desc": "300,000+ utilisateurs inscrits. Rejoignez la révolution SARAL.", "eco.partner": "Devenir Partenaire",
  "eco.validator.title": "Validateur", "eco.validator.desc": "Sécurisez le réseau et gagnez des récompenses.", "eco.validator.metric": "69K+ actifs",
  "eco.ambassador.title": "Ambassadeur", "eco.ambassador.desc": "Représentez MST mondialement.", "eco.ambassador.metric": "Portée mondiale",
  "eco.grants.title": "Subventions", "eco.grants.desc": "Demandez un financement pour construire sur MST.", "eco.grants.metric": "Candidatures ouvertes",
  "eco.developer.title": "Développeur", "eco.developer.desc": "Construisez avec une compatibilité EVM complète.", "eco.developer.metric": "Compatible EVM",
  "usecases.label": "20+ Industries", "usecases.title": "Cas d'Usage", "usecases.desc": "MST alimente des applications critiques.",
  "blogs.label": "Restez Informé", "blogs.title": "Dernières", "blogs.title2": "Actualités", "blogs.readMore": "Lire Plus",
  "security.label": "Sécurisé par PoSA", "security.title": "Construit sur", "security.title2": "la Pureté Structurelle.", "security.desc": "69,000+ validateurs, 161,000+ portefeuilles, 300,000+ utilisateurs.", "security.readDocs": "Lire la Documentation",
  "footer.desc": "Blockchain Layer-1 de nouvelle génération. Infrastructure SARAL.", "footer.ecosystem": "Écosystème", "footer.resources": "Ressources", "footer.contact": "Contact", "footer.newsletter": "Newsletter", "footer.submit": "Soumettre",
  "footer.rights": "© 2025 MST Blockchain. TOUS DROITS RÉSERVÉS.", "footer.emailPlaceholder": "VOTRE EMAIL",
  "grants.back": "Retour", "grants.label": "Financer l'Innovation", "grants.title": "Subventions MST", "grants.title2": "Programme", "grants.desc": "Soutenir les constructeurs.", "grants.apply": "Postuler", "grants.requirements": "Exigences", "grants.deliverables": "Livrables", "grants.process": "Processus",
  "amb.back": "Retour", "amb.label": "Rejoignez le Mouvement", "amb.title": "Ambassadeur MST", "amb.title2": "Programme", "amb.desc": "Représentez MST dans votre région.", "amb.apply": "Postuler", "amb.perks": "Avantages", "amb.benefits": "Avantages du Programme",
  "academy.back": "Retour", "academy.label": "Apprendre Web3", "academy.title": "MST", "academy.title2": "Académie", "academy.desc": "Maîtrisez le développement blockchain.", "academy.allModules": "Tous", "academy.fundamentals": "Fondamentaux", "academy.architecture": "Architecture", "academy.development": "Développement", "academy.deployment": "Déploiement", "academy.security": "Sécurité", "academy.lessons": "Leçons", "academy.assessment": "Évaluation", "academy.passingScore": "Note Minimale", "academy.startModule": "Démarrer le Module",
};

const de: TranslationMap = {
  "nav.build": "Bauen", "nav.products": "Produkte", "nav.explorer": "Explorer", "nav.usecases": "Anwendungsfälle", "nav.grants": "Förderungen", "nav.ambassador": "Botschafter", "nav.academy": "Akademie", "nav.join": "Ökosystem Beitreten",
  "hero.badge": "EVM Layer-1 Blockchain der nächsten Generation", "hero.title1": "ENGINEERING", "hero.desc": "MST Blockchain ist eine EVM-kompatible Layer-1-Blockchain der nächsten Generation, die Web3", "hero.desc2": "sicher, zugänglich und erschwinglich", "hero.desc3": "für alle macht.", "hero.explore": "Ökosystem Erkunden", "hero.docs": "Docs Lesen",
  "hero.validators": "Validatoren", "hero.wallets": "Erstellte Wallets", "hero.users": "Registrierte Benutzer", "hero.blocktime": "Blockzeit",
  "saral.simple": "Einfach", "saral.accessible": "Zugänglich", "saral.reliable": "Zuverlässig", "saral.affordable": "Erschwinglich", "saral.limitless": "Grenzenlos",
  "what.label": "01 / Grundlage", "what.title": "Was ist", "what.desc": "MST Blockchain ist eine EVM-kompatible Layer-1 der nächsten Generation.",
  "what.consensus": "Konsens", "what.posa": "Proof of Staked Authority", "what.blocktime": "3s Block · EVM kompatibel",
  "what.evm.title": "EVM Kompatibel", "what.evm.desc": "Voll kompatibel mit der Ethereum Virtual Machine. Deployen Sie Ihre Solidity-Verträge direkt.", "what.evm.cta": "Architektur ansehen", "what.evm.accent": "Layer-1 Infrastruktur",
  "what.posa.title": "PoSA Konsens", "what.posa.desc": "Konsensmechanismus mit 69.000+ Validatoren. 3 Sekunden Blockzeit.", "what.posa.cta": "Validatoren erkunden", "what.posa.accent": "69K+ Validatoren",
  "what.saral.title": "SARAL Framework", "what.saral.desc": "Einfach, Zugänglich, Zuverlässig, Erschwinglich und Grenzenlos.", "what.saral.cta": "SARAL lernen", "what.saral.accent": "Für Alle",
  "products.label": "SARAL Infrastruktur", "products.title": "Ökosystem", "products.title2": "Produkte", "products.explore": "Erkunden",
  "validator.join": "Treten Sie bei", "validator.validators": "Validatoren", "validator.desc": "Helfen Sie, das MST-Netzwerk zu sichern.", "validator.active": "Aktive Validatoren", "validator.uptime": "Netzwerk-Uptime", "validator.blocktime": "Blockzeit", "validator.become": "Validator werden",
  "explorer.label": "Live Netzwerk", "explorer.title": "MST Netzwerk", "explorer.title2": "Explorer", "explorer.live": "Live — 3s Block",
  "explorer.totalTx": "Gesamte Transaktionen", "explorer.gasPrice": "Gas-Preis", "explorer.avgBlock": "Durchschn. Blockzeit", "explorer.activeVal": "Aktive Validatoren",
  "explorer.latestBlocks": "Neueste Blöcke", "explorer.latestTx": "Neueste Transaktionen", "explorer.visit": "MSTScan besuchen",
  "eco.label": "Wachsende Gemeinschaft", "eco.title": "Treten Sie unserem", "eco.title2": "Ökosystem bei", "eco.desc": "300.000+ registrierte Benutzer. Werden Sie Teil der SARAL-Revolution.", "eco.partner": "Partner werden",
  "eco.validator.title": "Validator", "eco.validator.desc": "Sichern Sie das MST-Netzwerk und verdienen Sie Staking-Belohnungen.", "eco.validator.metric": "69K+ aktiv",
  "eco.ambassador.title": "Botschafter", "eco.ambassador.desc": "Vertreten Sie MST weltweit.", "eco.ambassador.metric": "Globale Reichweite",
  "eco.grants.title": "Förderungen", "eco.grants.desc": "Bewerben Sie sich um Finanzierung für innovative dApps.", "eco.grants.metric": "Bewerbungen offen",
  "eco.developer.title": "Entwickler", "eco.developer.desc": "Bauen Sie mit voller EVM-Kompatibilität.", "eco.developer.metric": "EVM kompatibel",
  "usecases.label": "20+ Branchen", "usecases.title": "Anwendungsfälle", "usecases.desc": "MST treibt geschäftskritische Anwendungen an.",
  "blogs.label": "Aktuell Bleiben", "blogs.title": "Neueste", "blogs.title2": "Updates", "blogs.readMore": "Mehr Lesen",
  "security.label": "Gesichert durch PoSA", "security.title": "Gebaut auf", "security.title2": "Strukturelle Reinheit.", "security.desc": "69.000+ Validatoren, 161.000+ Wallets, 300.000+ Benutzer.", "security.readDocs": "Dokumentation lesen",
  "footer.desc": "Layer-1 Blockchain der nächsten Generation. SARAL Infrastruktur.", "footer.ecosystem": "Ökosystem", "footer.resources": "Ressourcen", "footer.contact": "Kontakt", "footer.newsletter": "Newsletter", "footer.submit": "Absenden",
  "footer.rights": "© 2025 MST Blockchain. ALLE RECHTE VORBEHALTEN.", "footer.emailPlaceholder": "IHRE EMAIL",
  "grants.back": "Zurück", "grants.label": "Innovation fördern", "grants.title": "MST Förderungen", "grants.title2": "Programm", "grants.desc": "Unterstützung für Bauherren.", "grants.apply": "Jetzt bewerben", "grants.requirements": "Anforderungen", "grants.deliverables": "Ergebnisse", "grants.process": "Prozess",
  "amb.back": "Zurück", "amb.label": "Bewegung beitreten", "amb.title": "MST Botschafter", "amb.title2": "Programm", "amb.desc": "Vertreten Sie MST in Ihrer Region.", "amb.apply": "Jetzt bewerben", "amb.perks": "Vorteile", "amb.benefits": "Programmvorteile",
  "academy.back": "Zurück", "academy.label": "Web3 lernen", "academy.title": "MST", "academy.title2": "Akademie", "academy.desc": "Meistern Sie die Blockchain-Entwicklung.", "academy.allModules": "Alle", "academy.fundamentals": "Grundlagen", "academy.architecture": "Architektur", "academy.development": "Entwicklung", "academy.deployment": "Bereitstellung", "academy.security": "Sicherheit", "academy.lessons": "Lektionen", "academy.assessment": "Bewertung", "academy.passingScore": "Bestehensgrenze", "academy.startModule": "Modul starten",
};

const ja: TranslationMap = {
  "nav.build": "構築", "nav.products": "製品", "nav.explorer": "エクスプローラー", "nav.usecases": "ユースケース", "nav.grants": "助成金", "nav.ambassador": "アンバサダー", "nav.academy": "アカデミー", "nav.join": "エコシステム参加",
  "hero.badge": "次世代 EVM レイヤー1 ブロックチェーン", "hero.title1": "エンジニアリング", "hero.desc": "MSTブロックチェーンは次世代EVM互換レイヤー1ブロックチェーンで、Web3を", "hero.desc2": "安全で、アクセスしやすく、手頃", "hero.desc3": "にすべての人に。", "hero.explore": "エコシステムを探索", "hero.docs": "ドキュメントを読む",
  "hero.validators": "バリデーター", "hero.wallets": "作成されたウォレット", "hero.users": "登録ユーザー", "hero.blocktime": "ブロックタイム",
  "saral.simple": "シンプル", "saral.accessible": "アクセスしやすい", "saral.reliable": "信頼性", "saral.affordable": "手頃", "saral.limitless": "無限",
  "what.label": "01 / 基盤", "what.title": "とは", "what.desc": "MSTは次世代EVM互換Layer-1ブロックチェーンです。",
  "what.consensus": "コンセンサス", "what.posa": "ステーク権威証明", "what.blocktime": "3秒ブロック · EVM互換",
  "what.evm.title": "EVM互換", "what.evm.desc": "Ethereum仮想マシンと完全互換。Solidityスマートコントラクトを直接デプロイ。", "what.evm.cta": "アーキテクチャ", "what.evm.accent": "Layer-1インフラ",
  "what.posa.title": "PoSAコンセンサス", "what.posa.desc": "69,000+バリデーターによるコンセンサス。3秒ブロックタイム。", "what.posa.cta": "バリデーター探索", "what.posa.accent": "69K+バリデーター",
  "what.saral.title": "SARALフレームワーク", "what.saral.desc": "シンプル、アクセス可能、信頼性、手頃、無限。", "what.saral.cta": "SARAL学習", "what.saral.accent": "すべての人に",
  "products.label": "SARALインフラ", "products.title": "エコシステム", "products.title2": "製品", "products.explore": "探索",
  "validator.join": "参加", "validator.validators": "バリデーター", "validator.desc": "PoSAでMSTネットワークを保護。", "validator.active": "アクティブバリデーター", "validator.uptime": "稼働時間", "validator.blocktime": "ブロックタイム", "validator.become": "バリデーターになる",
  "explorer.label": "ライブネットワーク", "explorer.title": "MSTネットワーク", "explorer.title2": "エクスプローラー", "explorer.live": "ライブ — 3秒ブロック",
  "explorer.totalTx": "総トランザクション", "explorer.gasPrice": "ガス価格", "explorer.avgBlock": "平均ブロック時間", "explorer.activeVal": "アクティブバリデーター",
  "explorer.latestBlocks": "最新ブロック", "explorer.latestTx": "最新トランザクション", "explorer.visit": "MSTScan訪問",
  "eco.label": "成長するコミュニティ", "eco.title": "参加する", "eco.title2": "エコシステム", "eco.desc": "300,000+登録ユーザー。SARAL革命に参加。", "eco.partner": "パートナーになる",
  "eco.validator.title": "バリデーター", "eco.validator.desc": "MSTネットワークを保護しステーキング報酬を獲得。", "eco.validator.metric": "69K+アクティブ",
  "eco.ambassador.title": "アンバサダー", "eco.ambassador.desc": "MSTをグローバルに代表。", "eco.ambassador.metric": "グローバルリーチ",
  "eco.grants.title": "助成金", "eco.grants.desc": "MST上の革新的なdApp構築に資金を申請。", "eco.grants.metric": "申請受付中",
  "eco.developer.title": "開発者", "eco.developer.desc": "完全EVM互換で構築。", "eco.developer.metric": "EVM互換",
  "usecases.label": "20+業界", "usecases.title": "ユースケース", "usecases.desc": "MSTは各業界の重要なアプリケーションを駆動。",
  "blogs.label": "最新情報", "blogs.title": "最新", "blogs.title2": "アップデート", "blogs.readMore": "もっと読む",
  "security.label": "PoSAで保護", "security.title": "構築基盤", "security.title2": "構造的純粋性。", "security.desc": "69,000+バリデーター、161,000+ウォレット、300,000+ユーザー。", "security.readDocs": "ドキュメントを読む",
  "footer.desc": "次世代EVM互換Layer-1。SARALインフラ。", "footer.ecosystem": "エコシステム", "footer.resources": "リソース", "footer.contact": "連絡先", "footer.newsletter": "ニュースレター", "footer.submit": "送信",
  "footer.rights": "© 2025 MSTブロックチェーン。全著作権所有。", "footer.emailPlaceholder": "メールアドレス",
  "grants.back": "戻る", "grants.label": "イノベーション支援", "grants.title": "MST助成金", "grants.title2": "プログラム", "grants.desc": "ビルダーを支援。", "grants.apply": "今すぐ応募", "grants.requirements": "要件", "grants.deliverables": "成果物", "grants.process": "プロセス",
  "amb.back": "戻る", "amb.label": "運動に参加", "amb.title": "MSTアンバサダー", "amb.title2": "プログラム", "amb.desc": "地域でMSTを代表。", "amb.apply": "今すぐ応募", "amb.perks": "特典", "amb.benefits": "プログラム特典",
  "academy.back": "戻る", "academy.label": "Web3学習", "academy.title": "MST", "academy.title2": "アカデミー", "academy.desc": "ブロックチェーン開発をマスター。", "academy.allModules": "すべて", "academy.fundamentals": "基礎", "academy.architecture": "アーキテクチャ", "academy.development": "開発", "academy.deployment": "デプロイ", "academy.security": "セキュリティ", "academy.lessons": "レッスン", "academy.assessment": "評価", "academy.passingScore": "合格点", "academy.startModule": "モジュール開始",
};

const ko: TranslationMap = {
  "nav.build": "구축", "nav.products": "제품", "nav.explorer": "탐색기", "nav.usecases": "사용 사례", "nav.grants": "보조금", "nav.ambassador": "앰배서더", "nav.academy": "아카데미", "nav.join": "생태계 참여",
  "hero.badge": "차세대 EVM 레이어-1 블록체인", "hero.title1": "엔지니어링", "hero.desc": "MST 블록체인은 차세대 EVM 호환 레이어-1 블록체인으로, Web3를", "hero.desc2": "안전하고, 접근 가능하며, 저렴하게", "hero.desc3": "모든 사람을 위해.", "hero.explore": "생태계 탐색", "hero.docs": "문서 읽기",
  "hero.validators": "검증자", "hero.wallets": "생성된 지갑", "hero.users": "등록 사용자", "hero.blocktime": "블록 시간",
  "saral.simple": "간단", "saral.accessible": "접근 가능", "saral.reliable": "신뢰성", "saral.affordable": "저렴", "saral.limitless": "무한",
  "what.label": "01 / 기반", "what.title": "란", "what.desc": "MST는 차세대 EVM 호환 Layer-1 블록체인입니다.",
  "what.consensus": "합의", "what.posa": "지분 증명 권한", "what.blocktime": "3초 블록 · EVM 호환",
  "what.evm.title": "EVM 호환", "what.evm.desc": "이더리움 가상 머신과 완전 호환. Solidity 스마트 계약을 직접 배포.", "what.evm.cta": "아키텍처 보기", "what.evm.accent": "Layer-1 인프라",
  "what.posa.title": "PoSA 합의", "what.posa.desc": "69,000+검증자가 네트워크를 보호. 3초 블록 시간.", "what.posa.cta": "검증자 탐색", "what.posa.accent": "69K+ 검증자",
  "what.saral.title": "SARAL 프레임워크", "what.saral.desc": "간단, 접근 가능, 신뢰, 저렴, 무한.", "what.saral.cta": "SARAL 학습", "what.saral.accent": "모두를 위해",
  "products.label": "SARAL 인프라", "products.title": "생태계", "products.title2": "제품", "products.explore": "탐색",
  "validator.join": "참여", "validator.validators": "검증자", "validator.desc": "PoSA로 MST 네트워크를 보호하세요.", "validator.active": "활성 검증자", "validator.uptime": "가동 시간", "validator.blocktime": "블록 시간", "validator.become": "검증자 되기",
  "explorer.label": "실시간 네트워크", "explorer.title": "MST 네트워크", "explorer.title2": "탐색기", "explorer.live": "실시간 — 3초 블록",
  "explorer.totalTx": "총 거래", "explorer.gasPrice": "가스 가격", "explorer.avgBlock": "평균 블록 시간", "explorer.activeVal": "활성 검증자",
  "explorer.latestBlocks": "최신 블록", "explorer.latestTx": "최신 거래", "explorer.visit": "MSTScan 방문",
  "eco.label": "성장하는 커뮤니티", "eco.title": "참여하세요", "eco.title2": "생태계", "eco.desc": "300,000+등록 사용자. SARAL 혁명에 참여하세요.", "eco.partner": "파트너 되기",
  "eco.validator.title": "검증자", "eco.validator.desc": "MST 네트워크를 보호하고 보상을 받으세요.", "eco.validator.metric": "69K+ 활성",
  "eco.ambassador.title": "앰배서더", "eco.ambassador.desc": "전 세계적으로 MST를 대표하세요.", "eco.ambassador.metric": "글로벌 도달",
  "eco.grants.title": "보조금", "eco.grants.desc": "MST에서 혁신적인 dApp을 구축하기 위한 자금을 신청하세요.", "eco.grants.metric": "신청 가능",
  "eco.developer.title": "개발자", "eco.developer.desc": "완전한 EVM 호환성으로 구축하세요.", "eco.developer.metric": "EVM 호환",
  "usecases.label": "20+ 산업", "usecases.title": "사용 사례", "usecases.desc": "MST는 산업 전반의 핵심 애플리케이션을 지원합니다.",
  "blogs.label": "최신 소식", "blogs.title": "최신", "blogs.title2": "업데이트", "blogs.readMore": "더 읽기",
  "security.label": "PoSA로 보호", "security.title": "기반", "security.title2": "구조적 순수성.", "security.desc": "69,000+ 검증자, 161,000+ 지갑, 300,000+ 사용자.", "security.readDocs": "문서 읽기",
  "footer.desc": "차세대 EVM 호환 Layer-1. SARAL 인프라.", "footer.ecosystem": "생태계", "footer.resources": "리소스", "footer.contact": "연락처", "footer.newsletter": "뉴스레터", "footer.submit": "제출",
  "footer.rights": "© 2025 MST 블록체인. 모든 권리 보유.", "footer.emailPlaceholder": "이메일",
  "grants.back": "돌아가기", "grants.label": "혁신 지원", "grants.title": "MST 보조금", "grants.title2": "프로그램", "grants.desc": "빌더를 지원합니다.", "grants.apply": "지금 신청", "grants.requirements": "요구 사항", "grants.deliverables": "산출물", "grants.process": "프로세스",
  "amb.back": "돌아가기", "amb.label": "운동에 참여", "amb.title": "MST 앰배서더", "amb.title2": "프로그램", "amb.desc": "지역에서 MST를 대표하세요.", "amb.apply": "지금 신청", "amb.perks": "혜택", "amb.benefits": "프로그램 혜택",
  "academy.back": "돌아가기", "academy.label": "Web3 학습", "academy.title": "MST", "academy.title2": "아카데미", "academy.desc": "블록체인 개발을 마스터하세요.", "academy.allModules": "전체", "academy.fundamentals": "기초", "academy.architecture": "아키텍처", "academy.development": "개발", "academy.deployment": "배포", "academy.security": "보안", "academy.lessons": "수업", "academy.assessment": "평가", "academy.passingScore": "합격 점수", "academy.startModule": "모듈 시작",
};

const ar: TranslationMap = {
  "nav.build": "بناء", "nav.products": "المنتجات", "nav.explorer": "المستكشف", "nav.usecases": "حالات الاستخدام", "nav.grants": "المنح", "nav.ambassador": "السفير", "nav.academy": "الأكاديمية", "nav.join": "انضم للنظام",
  "hero.badge": "بلوكشين EVM الطبقة الأولى من الجيل القادم", "hero.title1": "هندسة", "hero.desc": "MST بلوكشين هي بلوكشين الطبقة الأولى متوافقة مع EVM من الجيل القادم، مصممة لجعل Web3", "hero.desc2": "آمنة وسهلة الوصول وبأسعار معقولة", "hero.desc3": "للجميع.", "hero.explore": "استكشف النظام", "hero.docs": "اقرأ الوثائق",
  "hero.validators": "المصادقون", "hero.wallets": "المحافظ المنشأة", "hero.users": "المستخدمون المسجلون", "hero.blocktime": "وقت الكتلة",
  "saral.simple": "بسيط", "saral.accessible": "متاح", "saral.reliable": "موثوق", "saral.affordable": "ميسور", "saral.limitless": "لا حدود",
  "what.label": "01 / الأساس", "what.title": "ما هو", "what.desc": "MST هي بلوكشين الطبقة الأولى من الجيل القادم متوافقة مع EVM.",
  "what.consensus": "الإجماع", "what.posa": "إثبات السلطة المرهونة", "what.blocktime": "3ث كتلة · متوافق EVM",
  "what.evm.title": "متوافق EVM", "what.evm.desc": "متوافق تماماً مع آلة إيثريوم الافتراضية.", "what.evm.cta": "عرض البنية", "what.evm.accent": "بنية الطبقة الأولى",
  "what.posa.title": "إجماع PoSA", "what.posa.desc": "69,000+ مصادق يؤمنون الشبكة. وقت كتلة 3 ثوانٍ.", "what.posa.cta": "استكشاف المصادقين", "what.posa.accent": "69K+ مصادق",
  "what.saral.title": "إطار SARAL", "what.saral.desc": "بسيط، متاح، موثوق، ميسور ولا حدود.", "what.saral.cta": "تعلم SARAL", "what.saral.accent": "للجميع",
  "products.label": "بنية SARAL", "products.title": "النظام", "products.title2": "المنتجات", "products.explore": "استكشاف",
  "validator.join": "انضم إلى", "validator.validators": "المصادقين", "validator.desc": "ساعد في تأمين شبكة MST.", "validator.active": "المصادقون النشطون", "validator.uptime": "وقت التشغيل", "validator.blocktime": "وقت الكتلة", "validator.become": "كن مصادقاً",
  "explorer.label": "شبكة مباشرة", "explorer.title": "شبكة MST", "explorer.title2": "المستكشف", "explorer.live": "مباشر — 3ث كتلة",
  "explorer.totalTx": "إجمالي المعاملات", "explorer.gasPrice": "سعر الغاز", "explorer.avgBlock": "متوسط وقت الكتلة", "explorer.activeVal": "المصادقون النشطون",
  "explorer.latestBlocks": "أحدث الكتل", "explorer.latestTx": "أحدث المعاملات", "explorer.visit": "زيارة MSTScan",
  "eco.label": "مجتمع متنامي", "eco.title": "انضم إلى", "eco.title2": "النظام البيئي", "eco.desc": "300,000+ مستخدم مسجل. كن جزءاً من ثورة SARAL.", "eco.partner": "كن شريكاً",
  "eco.validator.title": "مصادق", "eco.validator.desc": "أمّن شبكة MST واكسب مكافآت.", "eco.validator.metric": "69K+ نشط",
  "eco.ambassador.title": "سفير", "eco.ambassador.desc": "مثّل MST عالمياً.", "eco.ambassador.metric": "وصول عالمي",
  "eco.grants.title": "المنح", "eco.grants.desc": "تقدم بطلب تمويل لبناء تطبيقات مبتكرة.", "eco.grants.metric": "الطلبات مفتوحة",
  "eco.developer.title": "مطور", "eco.developer.desc": "ابنِ مع توافق EVM الكامل.", "eco.developer.metric": "متوافق EVM",
  "usecases.label": "20+ صناعة", "usecases.title": "حالات الاستخدام", "usecases.desc": "MST يدعم تطبيقات حرجة عبر الصناعات.",
  "blogs.label": "ابقَ محدثاً", "blogs.title": "آخر", "blogs.title2": "التحديثات", "blogs.readMore": "اقرأ المزيد",
  "security.label": "مؤمن بـ PoSA", "security.title": "مبني على", "security.title2": "النقاء الهيكلي.", "security.desc": "69,000+ مصادق، 161,000+ محفظة، 300,000+ مستخدم.", "security.readDocs": "اقرأ الوثائق",
  "footer.desc": "بلوكشين الطبقة الأولى من الجيل القادم. بنية SARAL.", "footer.ecosystem": "النظام البيئي", "footer.resources": "الموارد", "footer.contact": "اتصل", "footer.newsletter": "النشرة", "footer.submit": "إرسال",
  "footer.rights": "© 2025 MST بلوكشين. جميع الحقوق محفوظة.", "footer.emailPlaceholder": "بريدك الإلكتروني",
  "grants.back": "العودة", "grants.label": "تمويل الابتكار", "grants.title": "منح MST", "grants.title2": "البرنامج", "grants.desc": "دعم البناة.", "grants.apply": "تقدم الآن", "grants.requirements": "المتطلبات", "grants.deliverables": "المخرجات", "grants.process": "العملية",
  "amb.back": "العودة", "amb.label": "انضم للحركة", "amb.title": "سفير MST", "amb.title2": "البرنامج", "amb.desc": "مثّل MST في منطقتك.", "amb.apply": "تقدم الآن", "amb.perks": "المزايا", "amb.benefits": "مزايا البرنامج",
  "academy.back": "العودة", "academy.label": "تعلم Web3", "academy.title": "MST", "academy.title2": "الأكاديمية", "academy.desc": "أتقن تطوير البلوكشين.", "academy.allModules": "الكل", "academy.fundamentals": "الأساسيات", "academy.architecture": "البنية", "academy.development": "التطوير", "academy.deployment": "النشر", "academy.security": "الأمن", "academy.lessons": "الدروس", "academy.assessment": "التقييم", "academy.passingScore": "درجة النجاح", "academy.startModule": "بدء الوحدة",
};

const pt: TranslationMap = {
  "nav.build": "Construir", "nav.products": "Produtos", "nav.explorer": "Explorador", "nav.usecases": "Casos de Uso", "nav.grants": "Subsídios", "nav.ambassador": "Embaixador", "nav.academy": "Academia", "nav.join": "Junte-se ao Ecossistema",
  "hero.badge": "Blockchain EVM Layer-1 de Nova Geração", "hero.title1": "ENGENHARIA", "hero.desc": "MST Blockchain é uma blockchain Layer-1 compatível com EVM de nova geração, projetada para tornar o Web3", "hero.desc2": "seguro, acessível e acessível", "hero.desc3": "para todos.", "hero.explore": "Explorar Ecossistema", "hero.docs": "Ler Docs",
  "hero.validators": "Validadores", "hero.wallets": "Carteiras Criadas", "hero.users": "Usuários Registrados", "hero.blocktime": "Tempo de Bloco",
  "saral.simple": "Simples", "saral.accessible": "Acessível", "saral.reliable": "Confiável", "saral.affordable": "Acessível", "saral.limitless": "Ilimitado",
  "what.label": "01 / Fundação", "what.title": "O que é", "what.desc": "MST é uma blockchain Layer-1 compatível com EVM de nova geração.",
  "what.consensus": "Consenso", "what.posa": "Prova de Autoridade Apostada", "what.blocktime": "3s bloco · Compatível EVM",
  "what.evm.title": "Compatível EVM", "what.evm.desc": "Totalmente compatível com a Máquina Virtual Ethereum.", "what.evm.cta": "Ver Arquitetura", "what.evm.accent": "Infraestrutura Layer-1",
  "what.posa.title": "Consenso PoSA", "what.posa.desc": "69.000+ validadores protegendo a rede. Bloco de 3 segundos.", "what.posa.cta": "Explorar Validadores", "what.posa.accent": "69K+ Validadores",
  "what.saral.title": "Framework SARAL", "what.saral.desc": "Simples, Acessível, Confiável, Acessível e Ilimitado.", "what.saral.cta": "Aprender SARAL", "what.saral.accent": "Para Todos",
  "products.label": "Infraestrutura SARAL", "products.title": "Ecossistema", "products.title2": "Produtos", "products.explore": "Explorar",
  "validator.join": "Junte-se a", "validator.validators": "Validadores", "validator.desc": "Ajude a proteger a rede MST.", "validator.active": "Validadores Ativos", "validator.uptime": "Tempo Ativo", "validator.blocktime": "Tempo de Bloco", "validator.become": "Seja um Validador",
  "explorer.label": "Rede ao Vivo", "explorer.title": "Rede MST", "explorer.title2": "Explorador", "explorer.live": "Ao Vivo — 3s Bloco",
  "explorer.totalTx": "Total Transações", "explorer.gasPrice": "Preço do Gas", "explorer.avgBlock": "Tempo Médio", "explorer.activeVal": "Validadores Ativos",
  "explorer.latestBlocks": "Últimos Blocos", "explorer.latestTx": "Últimas Transações", "explorer.visit": "Visitar MSTScan",
  "eco.label": "Comunidade Crescente", "eco.title": "Junte-se ao Nosso", "eco.title2": "Ecossistema", "eco.desc": "300.000+ usuários registrados. Seja parte da revolução SARAL.", "eco.partner": "Ser Parceiro",
  "eco.validator.title": "Validador", "eco.validator.desc": "Proteja a rede MST e ganhe recompensas.", "eco.validator.metric": "69K+ ativos",
  "eco.ambassador.title": "Embaixador", "eco.ambassador.desc": "Represente MST globalmente.", "eco.ambassador.metric": "Alcance global",
  "eco.grants.title": "Subsídios", "eco.grants.desc": "Solicite financiamento para construir dApps inovadores.", "eco.grants.metric": "Inscrições abertas",
  "eco.developer.title": "Desenvolvedor", "eco.developer.desc": "Construa com compatibilidade EVM completa.", "eco.developer.metric": "Compatível EVM",
  "usecases.label": "20+ Indústrias", "usecases.title": "Casos de Uso", "usecases.desc": "MST alimenta aplicações críticas em todas as indústrias.",
  "blogs.label": "Fique Atualizado", "blogs.title": "Últimas", "blogs.title2": "Atualizações", "blogs.readMore": "Ler Mais",
  "security.label": "Protegido por PoSA", "security.title": "Construído sobre", "security.title2": "Pureza Estrutural.", "security.desc": "69.000+ validadores, 161.000+ carteiras, 300.000+ usuários.", "security.readDocs": "Ler Documentação",
  "footer.desc": "Blockchain Layer-1 de nova geração. Infraestrutura SARAL.", "footer.ecosystem": "Ecossistema", "footer.resources": "Recursos", "footer.contact": "Contato", "footer.newsletter": "Newsletter", "footer.submit": "Enviar",
  "footer.rights": "© 2025 MST Blockchain. TODOS OS DIREITOS RESERVADOS.", "footer.emailPlaceholder": "SEU EMAIL",
  "grants.back": "Voltar", "grants.label": "Financiando Inovação", "grants.title": "Subsídios MST", "grants.title2": "Programa", "grants.desc": "Apoiando construtores.", "grants.apply": "Aplicar Agora", "grants.requirements": "Requisitos", "grants.deliverables": "Entregas", "grants.process": "Processo",
  "amb.back": "Voltar", "amb.label": "Junte-se ao Movimento", "amb.title": "Embaixador MST", "amb.title2": "Programa", "amb.desc": "Represente MST na sua região.", "amb.apply": "Aplicar Agora", "amb.perks": "Benefícios", "amb.benefits": "Benefícios do Programa",
  "academy.back": "Voltar", "academy.label": "Aprenda Web3", "academy.title": "MST", "academy.title2": "Academia", "academy.desc": "Domine o desenvolvimento blockchain.", "academy.allModules": "Todos", "academy.fundamentals": "Fundamentos", "academy.architecture": "Arquitetura", "academy.development": "Desenvolvimento", "academy.deployment": "Implantação", "academy.security": "Segurança", "academy.lessons": "Lições", "academy.assessment": "Avaliação", "academy.passingScore": "Nota Mínima", "academy.startModule": "Iniciar Módulo",
};

const ru: TranslationMap = {
  "nav.build": "Строить", "nav.products": "Продукты", "nav.explorer": "Обозреватель", "nav.usecases": "Кейсы", "nav.grants": "Гранты", "nav.ambassador": "Амбассадор", "nav.academy": "Академия", "nav.join": "Присоединиться",
  "hero.badge": "EVM Layer-1 Блокчейн Нового Поколения", "hero.title1": "ИНЖЕНЕРИЯ", "hero.desc": "MST Blockchain — это блокчейн Layer-1 нового поколения, совместимый с EVM, созданный для того, чтобы Web3 стал", "hero.desc2": "безопасным, доступным и недорогим", "hero.desc3": "для всех.", "hero.explore": "Исследовать Экосистему", "hero.docs": "Читать Документацию",
  "hero.validators": "Валидаторы", "hero.wallets": "Создано Кошельков", "hero.users": "Зарегистрировано", "hero.blocktime": "Время Блока",
  "saral.simple": "Простой", "saral.accessible": "Доступный", "saral.reliable": "Надёжный", "saral.affordable": "Доступный", "saral.limitless": "Безграничный",
  "what.label": "01 / Основа", "what.title": "Что такое", "what.desc": "MST — это блокчейн Layer-1 нового поколения, совместимый с EVM.",
  "what.consensus": "Консенсус", "what.posa": "Proof of Staked Authority", "what.blocktime": "3с блок · EVM совместимый",
  "what.evm.title": "EVM Совместимый", "what.evm.desc": "Полностью совместим с виртуальной машиной Ethereum.", "what.evm.cta": "Архитектура", "what.evm.accent": "Инфраструктура Layer-1",
  "what.posa.title": "Консенсус PoSA", "what.posa.desc": "69,000+ валидаторов защищают сеть. Блок за 3 секунды.", "what.posa.cta": "Валидаторы", "what.posa.accent": "69K+ валидаторов",
  "what.saral.title": "Фреймворк SARAL", "what.saral.desc": "Простой, Доступный, Надёжный, Экономичный, Безграничный.", "what.saral.cta": "Узнать о SARAL", "what.saral.accent": "Для всех",
  "products.label": "Инфраструктура SARAL", "products.title": "Экосистема", "products.title2": "Продукты", "products.explore": "Исследовать",
  "validator.join": "Присоединяйтесь к", "validator.validators": "Валидаторам", "validator.desc": "Помогите защитить сеть MST.", "validator.active": "Активные валидаторы", "validator.uptime": "Аптайм сети", "validator.blocktime": "Время блока", "validator.become": "Стать валидатором",
  "explorer.label": "Сеть онлайн", "explorer.title": "Сеть MST", "explorer.title2": "Обозреватель", "explorer.live": "Онлайн — 3с блок",
  "explorer.totalTx": "Всего транзакций", "explorer.gasPrice": "Цена газа", "explorer.avgBlock": "Средн. время блока", "explorer.activeVal": "Активные валидаторы",
  "explorer.latestBlocks": "Последние блоки", "explorer.latestTx": "Последние транзакции", "explorer.visit": "Посетить MSTScan",
  "eco.label": "Растущее сообщество", "eco.title": "Присоединяйтесь к", "eco.title2": "Экосистеме", "eco.desc": "300,000+ пользователей. Станьте частью революции SARAL.", "eco.partner": "Стать партнёром",
  "eco.validator.title": "Валидатор", "eco.validator.desc": "Защитите сеть MST и получайте награды.", "eco.validator.metric": "69K+ активных",
  "eco.ambassador.title": "Амбассадор", "eco.ambassador.desc": "Представляйте MST по всему миру.", "eco.ambassador.metric": "Глобальный охват",
  "eco.grants.title": "Гранты", "eco.grants.desc": "Подайте заявку на финансирование для создания dApp.", "eco.grants.metric": "Приём заявок",
  "eco.developer.title": "Разработчик", "eco.developer.desc": "Стройте с полной совместимостью EVM.", "eco.developer.metric": "EVM совместимый",
  "usecases.label": "20+ отраслей", "usecases.title": "Кейсы", "usecases.desc": "MST поддерживает критически важные приложения.",
  "blogs.label": "Будьте в курсе", "blogs.title": "Последние", "blogs.title2": "Обновления", "blogs.readMore": "Читать далее",
  "security.label": "Защищён PoSA", "security.title": "Построен на", "security.title2": "Структурной Чистоте.", "security.desc": "69,000+ валидаторов, 161,000+ кошельков, 300,000+ пользователей.", "security.readDocs": "Читать документацию",
  "footer.desc": "Блокчейн Layer-1 нового поколения. Инфраструктура SARAL.", "footer.ecosystem": "Экосистема", "footer.resources": "Ресурсы", "footer.contact": "Контакт", "footer.newsletter": "Рассылка", "footer.submit": "Отправить",
  "footer.rights": "© 2025 MST Blockchain. ВСЕ ПРАВА ЗАЩИЩЕНЫ.", "footer.emailPlaceholder": "ВАШ EMAIL",
  "grants.back": "Назад", "grants.label": "Финансирование инноваций", "grants.title": "Гранты MST", "grants.title2": "Программа", "grants.desc": "Поддержка строителей.", "grants.apply": "Подать заявку", "grants.requirements": "Требования", "grants.deliverables": "Результаты", "grants.process": "Процесс",
  "amb.back": "Назад", "amb.label": "Присоединяйтесь", "amb.title": "Амбассадор MST", "amb.title2": "Программа", "amb.desc": "Представляйте MST в вашем регионе.", "amb.apply": "Подать заявку", "amb.perks": "Преимущества", "amb.benefits": "Преимущества программы",
  "academy.back": "Назад", "academy.label": "Изучайте Web3", "academy.title": "MST", "academy.title2": "Академия", "academy.desc": "Освойте разработку блокчейн.", "academy.allModules": "Все", "academy.fundamentals": "Основы", "academy.architecture": "Архитектура", "academy.development": "Разработка", "academy.deployment": "Развёртывание", "academy.security": "Безопасность", "academy.lessons": "Уроки", "academy.assessment": "Оценка", "academy.passingScore": "Проходной балл", "academy.startModule": "Начать модуль",
};

const tr: TranslationMap = {
  "nav.build": "İnşa Et", "nav.products": "Ürünler", "nav.explorer": "Gezgin", "nav.usecases": "Kullanım", "nav.grants": "Hibeler", "nav.ambassador": "Elçi", "nav.academy": "Akademi", "nav.join": "Ekosisteme Katıl",
  "hero.badge": "Yeni Nesil EVM Layer-1 Blok Zinciri", "hero.title1": "MÜHENDİSLİK", "hero.desc": "MST Blockchain, Web3'ü", "hero.desc2": "güvenli, erişilebilir ve uygun fiyatlı", "hero.desc3": "herkes için yapan yeni nesil EVM uyumlu Layer-1 blok zinciridir.", "hero.explore": "Ekosistemi Keşfet", "hero.docs": "Belgeleri Oku",
  "hero.validators": "Doğrulayıcılar", "hero.wallets": "Oluşturulan Cüzdanlar", "hero.users": "Kayıtlı Kullanıcılar", "hero.blocktime": "Blok Süresi",
  "saral.simple": "Basit", "saral.accessible": "Erişilebilir", "saral.reliable": "Güvenilir", "saral.affordable": "Uygun", "saral.limitless": "Sınırsız",
  "what.label": "01 / Temel", "what.title": "Nedir", "what.desc": "MST, yeni nesil EVM uyumlu Layer-1 blok zinciridir.",
  "what.consensus": "Konsensüs", "what.posa": "Stake Edilmiş Otorite Kanıtı", "what.blocktime": "3s blok · EVM uyumlu",
  "what.evm.title": "EVM Uyumlu", "what.evm.desc": "Ethereum Sanal Makinesi ile tam uyumlu.", "what.evm.cta": "Mimariyi Gör", "what.evm.accent": "Layer-1 Altyapı",
  "what.posa.title": "PoSA Konsensüs", "what.posa.desc": "69.000+ doğrulayıcı ağı koruyor. 3 saniye blok süresi.", "what.posa.cta": "Doğrulayıcıları Keşfet", "what.posa.accent": "69K+ Doğrulayıcı",
  "what.saral.title": "SARAL Çerçevesi", "what.saral.desc": "Basit, Erişilebilir, Güvenilir, Uygun ve Sınırsız.", "what.saral.cta": "SARAL Öğren", "what.saral.accent": "Herkes İçin",
  "products.label": "SARAL Altyapı", "products.title": "Ekosistem", "products.title2": "Ürünler", "products.explore": "Keşfet",
  "validator.join": "Katılın", "validator.validators": "Doğrulayıcılar", "validator.desc": "MST ağını korumaya yardım edin.", "validator.active": "Aktif Doğrulayıcılar", "validator.uptime": "Ağ Çalışma Süresi", "validator.blocktime": "Blok Süresi", "validator.become": "Doğrulayıcı Olun",
  "explorer.label": "Canlı Ağ", "explorer.title": "MST Ağı", "explorer.title2": "Gezgin", "explorer.live": "Canlı — 3s Blok",
  "explorer.totalTx": "Toplam İşlem", "explorer.gasPrice": "Gas Fiyatı", "explorer.avgBlock": "Ort. Blok Süresi", "explorer.activeVal": "Aktif Doğrulayıcılar",
  "explorer.latestBlocks": "Son Bloklar", "explorer.latestTx": "Son İşlemler", "explorer.visit": "MSTScan Ziyaret",
  "eco.label": "Büyüyen Topluluk", "eco.title": "Katılın", "eco.title2": "Ekosisteme", "eco.desc": "300.000+ kayıtlı kullanıcı. SARAL devrimine katılın.", "eco.partner": "Ortak Olun",
  "eco.validator.title": "Doğrulayıcı", "eco.validator.desc": "MST ağını koruyun ve ödül kazanın.", "eco.validator.metric": "69K+ aktif",
  "eco.ambassador.title": "Elçi", "eco.ambassador.desc": "MST'yi küresel olarak temsil edin.", "eco.ambassador.metric": "Küresel erişim",
  "eco.grants.title": "Hibeler", "eco.grants.desc": "MST üzerinde yenilikçi dApp'ler için fon başvurusu yapın.", "eco.grants.metric": "Başvurular açık",
  "eco.developer.title": "Geliştirici", "eco.developer.desc": "Tam EVM uyumluluğu ile geliştirin.", "eco.developer.metric": "EVM uyumlu",
  "usecases.label": "20+ Sektör", "usecases.title": "Kullanım Alanları", "usecases.desc": "MST sektörler arası kritik uygulamaları destekler.",
  "blogs.label": "Güncel Kalın", "blogs.title": "Son", "blogs.title2": "Güncellemeler", "blogs.readMore": "Devamını Oku",
  "security.label": "PoSA ile Güvenli", "security.title": "Üzerine İnşa", "security.title2": "Yapısal Saflık.", "security.desc": "69.000+ doğrulayıcı, 161.000+ cüzdan, 300.000+ kullanıcı.", "security.readDocs": "Belgeleri Oku",
  "footer.desc": "Yeni nesil EVM uyumlu Layer-1. SARAL altyapı.", "footer.ecosystem": "Ekosistem", "footer.resources": "Kaynaklar", "footer.contact": "İletişim", "footer.newsletter": "Bülten", "footer.submit": "Gönder",
  "footer.rights": "© 2025 MST Blockchain. TÜM HAKLARI SAKLIDIR.", "footer.emailPlaceholder": "E-POSTA",
  "grants.back": "Geri", "grants.label": "İnovasyonu Finanse Et", "grants.title": "MST Hibeleri", "grants.title2": "Program", "grants.desc": "İnşacıları destekliyoruz.", "grants.apply": "Şimdi Başvur", "grants.requirements": "Gereksinimler", "grants.deliverables": "Çıktılar", "grants.process": "Süreç",
  "amb.back": "Geri", "amb.label": "Harekete Katıl", "amb.title": "MST Elçisi", "amb.title2": "Program", "amb.desc": "Bölgenizde MST'yi temsil edin.", "amb.apply": "Şimdi Başvur", "amb.perks": "Avantajlar", "amb.benefits": "Program Avantajları",
  "academy.back": "Geri", "academy.label": "Web3 Öğren", "academy.title": "MST", "academy.title2": "Akademi", "academy.desc": "Blok zinciri geliştirmeyi öğrenin.", "academy.allModules": "Tümü", "academy.fundamentals": "Temel", "academy.architecture": "Mimari", "academy.development": "Geliştirme", "academy.deployment": "Dağıtım", "academy.security": "Güvenlik", "academy.lessons": "Dersler", "academy.assessment": "Değerlendirme", "academy.passingScore": "Geçme Notu", "academy.startModule": "Modüle Başla",
};

const translations: Translations = { en, hi, zh, es, fr, de, ja, ko, ar, pt, ru, tr };

function getTranslation(lang: LangCode, key: string): string {
  return translations[lang]?.[key] ?? translations.en?.[key] ?? key;
}

type LanguageContextType = {
  lang: LangCode;
  setLang: (lang: LangCode) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
};

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => {},
  t: (key) => key,
  dir: "ltr",
});

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLangState] = useState<LangCode>("en");

  const currentLangMeta = LANGUAGES.find((l) => l.code === lang);
  const dir = currentLangMeta?.dir === "rtl" ? "rtl" : "ltr";

  const setLang = (code: LangCode) => {
    setLangState(code);
    localStorage.setItem("mst-lang", code);
    document.documentElement.dir = LANGUAGES.find((l) => l.code === code)?.dir === "rtl" ? "rtl" : "ltr";
  };

  const t = (key: string) => getTranslation(lang, key);

  useEffect(() => {
    const saved = localStorage.getItem("mst-lang");
    if (saved) {
      setLangState(saved);
      document.documentElement.dir = LANGUAGES.find((l) => l.code === saved)?.dir === "rtl" ? "rtl" : "ltr";
    }
  }, []);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};
