import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type LangCode = string;

export const LANGUAGES: { code: LangCode; name: string; native: string; dir?: "rtl" }[] = [
  { code: "en", name: "English", native: "English" },
  { code: "hi", name: "Hindi", native: "हिन्दी" },
  { code: "bn", name: "Bengali", native: "বাংলা" },
  { code: "te", name: "Telugu", native: "తెలుగు" },
  { code: "ta", name: "Tamil", native: "தமிழ்" },
  { code: "mr", name: "Marathi", native: "मराठी" },
  { code: "gu", name: "Gujarati", native: "ગુજરાતી" },
  { code: "kn", name: "Kannada", native: "ಕನ್ನಡ" },
  { code: "ml", name: "Malayalam", native: "മലയാളം" },
  { code: "pa", name: "Punjabi", native: "ਪੰਜਾਬੀ" },
  { code: "or", name: "Odia", native: "ଓଡ଼ିଆ" },
  { code: "as", name: "Assamese", native: "অসমীয়া" },
  { code: "ur", name: "Urdu", native: "اردو", dir: "rtl" },
  { code: "ne", name: "Nepali", native: "नेपाली" },
  { code: "si", name: "Sinhala", native: "සිංහල" },
  { code: "zh", name: "Chinese", native: "中文" },
  { code: "ja", name: "Japanese", native: "日本語" },
  { code: "ko", name: "Korean", native: "한국어" },
  { code: "es", name: "Spanish", native: "Español" },
  { code: "fr", name: "French", native: "Français" },
  { code: "de", name: "German", native: "Deutsch" },
  { code: "pt", name: "Portuguese", native: "Português" },
  { code: "ru", name: "Russian", native: "Русский" },
  { code: "ar", name: "Arabic", native: "العربية", dir: "rtl" },
  { code: "tr", name: "Turkish", native: "Türkçe" },
  { code: "vi", name: "Vietnamese", native: "Tiếng Việt" },
  { code: "th", name: "Thai", native: "ไทย" },
  { code: "id", name: "Indonesian", native: "Bahasa Indonesia" },
  { code: "ms", name: "Malay", native: "Bahasa Melayu" },
  { code: "fil", name: "Filipino", native: "Filipino" },
  { code: "it", name: "Italian", native: "Italiano" },
  { code: "nl", name: "Dutch", native: "Nederlands" },
  { code: "pl", name: "Polish", native: "Polski" },
  { code: "uk", name: "Ukrainian", native: "Українська" },
  { code: "cs", name: "Czech", native: "Čeština" },
  { code: "sk", name: "Slovak", native: "Slovenčina" },
  { code: "ro", name: "Romanian", native: "Română" },
  { code: "hu", name: "Hungarian", native: "Magyar" },
  { code: "sv", name: "Swedish", native: "Svenska" },
  { code: "da", name: "Danish", native: "Dansk" },
  { code: "no", name: "Norwegian", native: "Norsk" },
  { code: "fi", name: "Finnish", native: "Suomi" },
  { code: "el", name: "Greek", native: "Ελληνικά" },
  { code: "bg", name: "Bulgarian", native: "Български" },
  { code: "hr", name: "Croatian", native: "Hrvatski" },
  { code: "sr", name: "Serbian", native: "Српски" },
  { code: "he", name: "Hebrew", native: "עברית", dir: "rtl" },
  { code: "fa", name: "Persian", native: "فارسی", dir: "rtl" },
  { code: "sw", name: "Swahili", native: "Kiswahili" },
  { code: "am", name: "Amharic", native: "አማርኛ" },
  { code: "my", name: "Burmese", native: "မြန်မာ" },
  { code: "km", name: "Khmer", native: "ខ្មែរ" },
  { code: "lo", name: "Lao", native: "ລາວ" },
  { code: "ka", name: "Georgian", native: "ქართული" },
  { code: "hy", name: "Armenian", native: "Հայերեն" },
  { code: "az", name: "Azerbaijani", native: "Azərbaycan" },
  { code: "uz", name: "Uzbek", native: "O'zbek" },
  { code: "kk", name: "Kazakh", native: "Қазақ" },
  { code: "mn", name: "Mongolian", native: "Монгол" },
  { code: "et", name: "Estonian", native: "Eesti" },
  { code: "lv", name: "Latvian", native: "Latviešu" },
  { code: "lt", name: "Lithuanian", native: "Lietuvių" },
];

// Translation keys
type TranslationMap = Record<string, string>;
type Translations = Record<LangCode, TranslationMap>;

const translations: Translations = {
  en: {
    "nav.build": "Build",
    "nav.products": "Products",
    "nav.explorer": "Explorer",
    "nav.usecases": "Use Cases",
    "nav.grants": "Grants",
    "nav.ambassador": "Ambassador",
    "nav.academy": "Academy",
    "nav.join": "Join Ecosystem",
    "hero.badge": "Next-Gen EVM Layer-1 Blockchain",
    "hero.title1": "ENGINEERING",
    "hero.desc": "MST Blockchain is a next-generation EVM Compatible Layer-1 blockchain, designed to make Web3",
    "hero.desc2": "secure, accessible, and affordable",
    "hero.desc3": "for everyone.",
    "hero.explore": "Explore Ecosystem",
    "hero.docs": "Read Docs",
    "hero.validators": "Validators",
    "hero.wallets": "Wallets Created",
    "hero.users": "Registered Users",
    "hero.blocktime": "Block Time",
    "section.foundation": "01 / Foundation",
    "section.whatismst": "What is",
    "section.products": "Ecosystem",
    "section.products2": "Products",
    "footer.newsletter": "Newsletter",
    "footer.submit": "Submit",
    "footer.contact": "Contact",
    "footer.ecosystem": "Ecosystem",
    "footer.resources": "Resources",
    "footer.rights": "© 2025 MST Blockchain. ALL RIGHTS RESERVED.",
    "saral.simple": "Simple",
    "saral.accessible": "Accessible",
    "saral.reliable": "Reliable",
    "saral.affordable": "Affordable",
    "saral.limitless": "Limitless",
  },
  hi: {
    "nav.build": "बनाएं",
    "nav.products": "उत्पाद",
    "nav.explorer": "एक्सप्लोरर",
    "nav.usecases": "उपयोग",
    "nav.grants": "अनुदान",
    "nav.ambassador": "राजदूत",
    "nav.academy": "अकादमी",
    "nav.join": "इकोसिस्टम जुड़ें",
    "hero.badge": "नेक्स्ट-जेन EVM लेयर-1 ब्लॉकचेन",
    "hero.title1": "इंजीनियरिंग",
    "hero.desc": "MST ब्लॉकचेन एक अगली पीढ़ी का EVM संगत लेयर-1 ब्लॉकचेन है, जिसे Web3 को",
    "hero.desc2": "सुरक्षित, सुलभ और किफायती",
    "hero.desc3": "सभी के लिए बनाया गया है।",
    "hero.explore": "इकोसिस्टम खोजें",
    "hero.docs": "डॉक्स पढ़ें",
    "hero.validators": "वैलिडेटर",
    "hero.wallets": "वॉलेट बनाए गए",
    "hero.users": "पंजीकृत उपयोगकर्ता",
    "hero.blocktime": "ब्लॉक टाइम",
    "section.foundation": "01 / नींव",
    "section.whatismst": "क्या है",
    "section.products": "इकोसिस्टम",
    "section.products2": "उत्पाद",
    "footer.newsletter": "समाचार पत्र",
    "footer.submit": "जमा करें",
    "footer.contact": "संपर्क",
    "footer.ecosystem": "इकोसिस्टम",
    "footer.resources": "संसाधन",
    "footer.rights": "© 2025 MST ब्लॉकचेन। सर्वाधिकार सुरक्षित।",
    "saral.simple": "सरल",
    "saral.accessible": "सुलभ",
    "saral.reliable": "विश्वसनीय",
    "saral.affordable": "किफायती",
    "saral.limitless": "असीमित",
  },
  zh: {
    "nav.build": "构建",
    "nav.products": "产品",
    "nav.explorer": "浏览器",
    "nav.usecases": "用例",
    "nav.grants": "资助",
    "nav.ambassador": "大使",
    "nav.academy": "学院",
    "nav.join": "加入生态",
    "hero.badge": "下一代 EVM Layer-1 区块链",
    "hero.title1": "工程",
    "hero.desc": "MST区块链是下一代EVM兼容Layer-1区块链，旨在使Web3",
    "hero.desc2": "安全、可访问且经济实惠",
    "hero.desc3": "面向所有人。",
    "hero.explore": "探索生态",
    "hero.docs": "阅读文档",
    "hero.validators": "验证者",
    "hero.wallets": "已创建钱包",
    "hero.users": "注册用户",
    "hero.blocktime": "出块时间",
    "section.foundation": "01 / 基础",
    "section.whatismst": "什么是",
    "section.products": "生态",
    "section.products2": "产品",
    "footer.newsletter": "通讯",
    "footer.submit": "提交",
    "footer.contact": "联系",
    "footer.ecosystem": "生态系统",
    "footer.resources": "资源",
    "footer.rights": "© 2025 MST区块链。保留所有权利。",
    "saral.simple": "简单",
    "saral.accessible": "可访问",
    "saral.reliable": "可靠",
    "saral.affordable": "实惠",
    "saral.limitless": "无限",
  },
  ja: {
    "nav.build": "構築",
    "nav.products": "製品",
    "nav.explorer": "エクスプローラー",
    "nav.usecases": "ユースケース",
    "nav.grants": "助成金",
    "nav.ambassador": "アンバサダー",
    "nav.academy": "アカデミー",
    "nav.join": "エコシステム参加",
    "hero.badge": "次世代 EVM レイヤー1 ブロックチェーン",
    "hero.title1": "エンジニアリング",
    "hero.desc": "MSTブロックチェーンは次世代EVM互換レイヤー1ブロックチェーンで、Web3を",
    "hero.desc2": "安全で、アクセスしやすく、手頃",
    "hero.desc3": "にすべての人に。",
    "hero.explore": "エコシステムを探索",
    "hero.docs": "ドキュメントを読む",
    "hero.validators": "バリデーター",
    "hero.wallets": "作成されたウォレット",
    "hero.users": "登録ユーザー",
    "hero.blocktime": "ブロックタイム",
    "section.foundation": "01 / 基盤",
    "section.whatismst": "とは",
    "section.products": "エコシステム",
    "section.products2": "製品",
    "footer.newsletter": "ニュースレター",
    "footer.submit": "送信",
    "footer.contact": "連絡先",
    "footer.ecosystem": "エコシステム",
    "footer.resources": "リソース",
    "footer.rights": "© 2025 MSTブロックチェーン。全著作権所有。",
    "saral.simple": "シンプル",
    "saral.accessible": "アクセスしやすい",
    "saral.reliable": "信頼性",
    "saral.affordable": "手頃",
    "saral.limitless": "無限",
  },
  ko: {
    "nav.build": "구축",
    "nav.products": "제품",
    "nav.explorer": "탐색기",
    "nav.usecases": "사용 사례",
    "nav.grants": "보조금",
    "nav.ambassador": "앰배서더",
    "nav.academy": "아카데미",
    "nav.join": "생태계 참여",
    "hero.badge": "차세대 EVM 레이어-1 블록체인",
    "hero.title1": "엔지니어링",
    "hero.desc": "MST 블록체인은 차세대 EVM 호환 레이어-1 블록체인으로, Web3를",
    "hero.desc2": "안전하고, 접근 가능하며, 저렴하게",
    "hero.desc3": "모든 사람을 위해.",
    "hero.explore": "생태계 탐색",
    "hero.docs": "문서 읽기",
    "hero.validators": "검증자",
    "hero.wallets": "생성된 지갑",
    "hero.users": "등록 사용자",
    "hero.blocktime": "블록 시간",
    "section.foundation": "01 / 기반",
    "section.whatismst": "란",
    "section.products": "생태계",
    "section.products2": "제품",
    "footer.newsletter": "뉴스레터",
    "footer.submit": "제출",
    "footer.contact": "연락처",
    "footer.ecosystem": "생태계",
    "footer.resources": "리소스",
    "footer.rights": "© 2025 MST 블록체인. 모든 권리 보유.",
    "saral.simple": "간단",
    "saral.accessible": "접근 가능",
    "saral.reliable": "신뢰성",
    "saral.affordable": "저렴",
    "saral.limitless": "무한",
  },
  es: {
    "nav.build": "Construir",
    "nav.products": "Productos",
    "nav.explorer": "Explorador",
    "nav.usecases": "Casos de Uso",
    "nav.grants": "Subvenciones",
    "nav.ambassador": "Embajador",
    "nav.academy": "Academia",
    "nav.join": "Unirse al Ecosistema",
    "hero.badge": "Blockchain EVM Layer-1 de Nueva Generación",
    "hero.title1": "INGENIERÍA",
    "hero.desc": "MST Blockchain es una blockchain Layer-1 compatible con EVM de nueva generación, diseñada para hacer Web3",
    "hero.desc2": "seguro, accesible y asequible",
    "hero.desc3": "para todos.",
    "hero.explore": "Explorar Ecosistema",
    "hero.docs": "Leer Docs",
    "hero.validators": "Validadores",
    "hero.wallets": "Billeteras Creadas",
    "hero.users": "Usuarios Registrados",
    "hero.blocktime": "Tiempo de Bloque",
    "section.foundation": "01 / Fundación",
    "section.whatismst": "¿Qué es",
    "section.products": "Ecosistema",
    "section.products2": "Productos",
    "footer.newsletter": "Boletín",
    "footer.submit": "Enviar",
    "footer.contact": "Contacto",
    "footer.ecosystem": "Ecosistema",
    "footer.resources": "Recursos",
    "footer.rights": "© 2025 MST Blockchain. TODOS LOS DERECHOS RESERVADOS.",
    "saral.simple": "Simple",
    "saral.accessible": "Accesible",
    "saral.reliable": "Confiable",
    "saral.affordable": "Asequible",
    "saral.limitless": "Sin Límites",
  },
  fr: {
    "nav.build": "Construire",
    "nav.products": "Produits",
    "nav.explorer": "Explorateur",
    "nav.usecases": "Cas d'Usage",
    "nav.grants": "Subventions",
    "nav.ambassador": "Ambassadeur",
    "nav.academy": "Académie",
    "nav.join": "Rejoindre l'Écosystème",
    "hero.badge": "Blockchain EVM Layer-1 Nouvelle Génération",
    "hero.title1": "INGÉNIERIE",
    "hero.desc": "MST Blockchain est une blockchain Layer-1 compatible EVM de nouvelle génération, conçue pour rendre Web3",
    "hero.desc2": "sécurisé, accessible et abordable",
    "hero.desc3": "pour tous.",
    "hero.explore": "Explorer l'Écosystème",
    "hero.docs": "Lire la Doc",
    "hero.validators": "Validateurs",
    "hero.wallets": "Portefeuilles Créés",
    "hero.users": "Utilisateurs Inscrits",
    "hero.blocktime": "Temps de Bloc",
    "section.foundation": "01 / Fondation",
    "section.whatismst": "Qu'est-ce que",
    "section.products": "Écosystème",
    "section.products2": "Produits",
    "footer.newsletter": "Newsletter",
    "footer.submit": "Soumettre",
    "footer.contact": "Contact",
    "footer.ecosystem": "Écosystème",
    "footer.resources": "Ressources",
    "footer.rights": "© 2025 MST Blockchain. TOUS DROITS RÉSERVÉS.",
    "saral.simple": "Simple",
    "saral.accessible": "Accessible",
    "saral.reliable": "Fiable",
    "saral.affordable": "Abordable",
    "saral.limitless": "Illimité",
  },
  de: {
    "nav.build": "Bauen",
    "nav.products": "Produkte",
    "nav.explorer": "Explorer",
    "nav.usecases": "Anwendungsfälle",
    "nav.grants": "Förderungen",
    "nav.ambassador": "Botschafter",
    "nav.academy": "Akademie",
    "nav.join": "Ökosystem Beitreten",
    "hero.badge": "EVM Layer-1 Blockchain der nächsten Generation",
    "hero.title1": "ENGINEERING",
    "hero.desc": "MST Blockchain ist eine EVM-kompatible Layer-1-Blockchain der nächsten Generation, die Web3",
    "hero.desc2": "sicher, zugänglich und erschwinglich",
    "hero.desc3": "für alle macht.",
    "hero.explore": "Ökosystem Erkunden",
    "hero.docs": "Docs Lesen",
    "hero.validators": "Validatoren",
    "hero.wallets": "Erstellte Wallets",
    "hero.users": "Registrierte Benutzer",
    "hero.blocktime": "Blockzeit",
    "section.foundation": "01 / Grundlage",
    "section.whatismst": "Was ist",
    "section.products": "Ökosystem",
    "section.products2": "Produkte",
    "footer.newsletter": "Newsletter",
    "footer.submit": "Absenden",
    "footer.contact": "Kontakt",
    "footer.ecosystem": "Ökosystem",
    "footer.resources": "Ressourcen",
    "footer.rights": "© 2025 MST Blockchain. ALLE RECHTE VORBEHALTEN.",
    "saral.simple": "Einfach",
    "saral.accessible": "Zugänglich",
    "saral.reliable": "Zuverlässig",
    "saral.affordable": "Erschwinglich",
    "saral.limitless": "Grenzenlos",
  },
  ar: {
    "nav.build": "بناء",
    "nav.products": "المنتجات",
    "nav.explorer": "المستكشف",
    "nav.usecases": "حالات الاستخدام",
    "nav.grants": "المنح",
    "nav.ambassador": "السفير",
    "nav.academy": "الأكاديمية",
    "nav.join": "انضم للنظام",
    "hero.badge": "بلوكشين EVM الطبقة الأولى من الجيل القادم",
    "hero.title1": "هندسة",
    "hero.desc": "MST بلوكشين هي بلوكشين الطبقة الأولى متوافقة مع EVM من الجيل القادم، مصممة لجعل Web3",
    "hero.desc2": "آمنة وسهلة الوصول وبأسعار معقولة",
    "hero.desc3": "للجميع.",
    "hero.explore": "استكشف النظام",
    "hero.docs": "اقرأ الوثائق",
    "hero.validators": "المصادقون",
    "hero.wallets": "المحافظ المنشأة",
    "hero.users": "المستخدمون المسجلون",
    "hero.blocktime": "وقت الكتلة",
    "section.foundation": "01 / الأساس",
    "section.whatismst": "ما هو",
    "section.products": "النظام",
    "section.products2": "المنتجات",
    "footer.newsletter": "النشرة",
    "footer.submit": "إرسال",
    "footer.contact": "اتصل",
    "footer.ecosystem": "النظام البيئي",
    "footer.resources": "الموارد",
    "footer.rights": "© 2025 MST بلوكشين. جميع الحقوق محفوظة.",
    "saral.simple": "بسيط",
    "saral.accessible": "متاح",
    "saral.reliable": "موثوق",
    "saral.affordable": "ميسور",
    "saral.limitless": "لا حدود",
  },
  pt: {
    "nav.build": "Construir",
    "nav.products": "Produtos",
    "nav.explorer": "Explorador",
    "nav.usecases": "Casos de Uso",
    "nav.grants": "Subsídios",
    "nav.ambassador": "Embaixador",
    "nav.academy": "Academia",
    "nav.join": "Junte-se ao Ecossistema",
    "hero.badge": "Blockchain EVM Layer-1 de Nova Geração",
    "hero.title1": "ENGENHARIA",
    "hero.desc": "MST Blockchain é uma blockchain Layer-1 compatível com EVM de nova geração, projetada para tornar o Web3",
    "hero.desc2": "seguro, acessível e acessível",
    "hero.desc3": "para todos.",
    "hero.explore": "Explorar Ecossistema",
    "hero.docs": "Ler Docs",
    "hero.validators": "Validadores",
    "hero.wallets": "Carteiras Criadas",
    "hero.users": "Usuários Registrados",
    "hero.blocktime": "Tempo de Bloco",
    "section.foundation": "01 / Fundação",
    "section.whatismst": "O que é",
    "section.products": "Ecossistema",
    "section.products2": "Produtos",
    "footer.newsletter": "Newsletter",
    "footer.submit": "Enviar",
    "footer.contact": "Contato",
    "footer.ecosystem": "Ecossistema",
    "footer.resources": "Recursos",
    "footer.rights": "© 2025 MST Blockchain. TODOS OS DIREITOS RESERVADOS.",
    "saral.simple": "Simples",
    "saral.accessible": "Acessível",
    "saral.reliable": "Confiável",
    "saral.affordable": "Acessível",
    "saral.limitless": "Ilimitado",
  },
  ru: {
    "nav.build": "Строить",
    "nav.products": "Продукты",
    "nav.explorer": "Обозреватель",
    "nav.usecases": "Кейсы",
    "nav.grants": "Гранты",
    "nav.ambassador": "Амбассадор",
    "nav.academy": "Академия",
    "nav.join": "Присоединиться",
    "hero.badge": "EVM Layer-1 Блокчейн Нового Поколения",
    "hero.title1": "ИНЖЕНЕРИЯ",
    "hero.desc": "MST Blockchain — это блокчейн Layer-1 нового поколения, совместимый с EVM, созданный для того, чтобы Web3 стал",
    "hero.desc2": "безопасным, доступным и недорогим",
    "hero.desc3": "для всех.",
    "hero.explore": "Исследовать Экосистему",
    "hero.docs": "Читать Документацию",
    "hero.validators": "Валидаторы",
    "hero.wallets": "Создано Кошельков",
    "hero.users": "Зарегистрировано",
    "hero.blocktime": "Время Блока",
    "section.foundation": "01 / Основа",
    "section.whatismst": "Что такое",
    "section.products": "Экосистема",
    "section.products2": "Продукты",
    "footer.newsletter": "Рассылка",
    "footer.submit": "Отправить",
    "footer.contact": "Контакт",
    "footer.ecosystem": "Экосистема",
    "footer.resources": "Ресурсы",
    "footer.rights": "© 2025 MST Blockchain. ВСЕ ПРАВА ЗАЩИЩЕНЫ.",
    "saral.simple": "Простой",
    "saral.accessible": "Доступный",
    "saral.reliable": "Надёжный",
    "saral.affordable": "Доступный",
    "saral.limitless": "Безграничный",
  },
  tr: {
    "nav.build": "İnşa Et",
    "nav.products": "Ürünler",
    "nav.explorer": "Gezgin",
    "nav.usecases": "Kullanım",
    "nav.grants": "Hibeler",
    "nav.ambassador": "Elçi",
    "nav.academy": "Akademi",
    "nav.join": "Ekosisteme Katıl",
    "hero.badge": "Yeni Nesil EVM Layer-1 Blok Zinciri",
    "hero.title1": "MÜHENDİSLİK",
    "hero.desc": "MST Blockchain, Web3'ü",
    "hero.desc2": "güvenli, erişilebilir ve uygun fiyatlı",
    "hero.desc3": "herkes için yapan yeni nesil EVM uyumlu Layer-1 blok zinciridir.",
    "hero.explore": "Ekosistemi Keşfet",
    "hero.docs": "Belgeleri Oku",
    "hero.validators": "Doğrulayıcılar",
    "hero.wallets": "Oluşturulan Cüzdanlar",
    "hero.users": "Kayıtlı Kullanıcılar",
    "hero.blocktime": "Blok Süresi",
    "section.foundation": "01 / Temel",
    "section.whatismst": "Nedir",
    "section.products": "Ekosistem",
    "section.products2": "Ürünler",
    "footer.newsletter": "Bülten",
    "footer.submit": "Gönder",
    "footer.contact": "İletişim",
    "footer.ecosystem": "Ekosistem",
    "footer.resources": "Kaynaklar",
    "footer.rights": "© 2025 MST Blockchain. TÜM HAKLARI SAKLIDIR.",
    "saral.simple": "Basit",
    "saral.accessible": "Erişilebilir",
    "saral.reliable": "Güvenilir",
    "saral.affordable": "Uygun",
    "saral.limitless": "Sınırsız",
  },
};

// For languages without explicit translations, fall back to English
function getTranslation(lang: LangCode, key: string): string {
  return translations[lang]?.[key] ?? translations.en?.[key] ?? key;
}

type LanguageContextType = {
  lang: LangCode;
  setLang: (lang: LangCode) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
};

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => {},
  t: (key) => key,
  dir: "ltr",
});

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLangState] = useState<LangCode>("en");

  const currentLangMeta = LANGUAGES.find((l) => l.code === lang);
  const dir = currentLangMeta?.dir === "rtl" ? "rtl" : "ltr";

  const setLang = (code: LangCode) => {
    setLangState(code);
    localStorage.setItem("mst-lang", code);
    document.documentElement.dir = LANGUAGES.find((l) => l.code === code)?.dir === "rtl" ? "rtl" : "ltr";
  };

  const t = (key: string) => getTranslation(lang, key);

  useEffect(() => {
    const saved = localStorage.getItem("mst-lang");
    if (saved) {
      setLangState(saved);
      document.documentElement.dir = LANGUAGES.find((l) => l.code === saved)?.dir === "rtl" ? "rtl" : "ltr";
    }
  }, []);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};
